/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicCandidateSummary } from './basicCandidateSummary';
import { EmployeeSummary } from './employeeSummary';
import { ModelStage } from './modelStage';
import { Vacancy } from './vacancy';


export interface Appointment { 
    /**
     * Data do compromisso.
     */
    date?: string;
    /**
     * Assunto do compromisso.
     */
    subject?: string;
    /**
     * Candidatos que participarão do compromisso.
     */
    candidates?: Array<BasicCandidateSummary>;
    /**
     * Local do compromisso.
     */
    site?: string;
    stage?: ModelStage;
    /**
     * Horário de início do compromisso.
     */
    startTime?: string;
    /**
     * Comentário do compromisso.
     */
    comment?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Horário de término do compromisso.
     */
    endTime?: string;
    /**
     * Colaboradores que participarão do compromisso para ajudar a avaliar os candidatos.
     */
    employees?: Array<EmployeeSummary>;
    vacancy?: Vacancy;
    /**
     * Identificador único da vaga &#9;do processo seletivo.
     */
    vacancyId?: string;
    /**
     * Identificador único da etapa do processo seletivo.
     */
    stageId?: string;
}
