/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BigFive } from './bigFive';


export interface Conscientiousness { 
    /**
     * Faceta de sentido de responsabilidade.
     */
    dutifulness?: number;
    /**
     * Faceta de cautela.
     */
    cautiousness?: number;
    /**
     * Valor desta dimensão
     */
    dimensionValue?: number;
    /**
     * Faceta de realização com esforço.
     */
    achievementStriving?: number;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Faceta de autoconfiança.
     */
    selfEfficacy?: number;
    /**
     * Faceta de autodisciplina.
     */
    selfDiscipline?: number;
    /**
     * Faceta de organização.
     */
    orderliness?: number;
    bigFive?: BigFive;
}
