/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DegreeDto = 'ELEMENTARY_SCHOOL' | 'HIGH_SCHOOL' | 'HIGHER_EDUCATION' | 'POST_GRADUATED' | 'MASTERS_DEGREE' | 'PHD_DEGREE' | 'POST_DOCTORATE';

export const DegreeDto = {
    ELEMENTARYSCHOOL: 'ELEMENTARY_SCHOOL' as DegreeDto,
    HIGHSCHOOL: 'HIGH_SCHOOL' as DegreeDto,
    HIGHEREDUCATION: 'HIGHER_EDUCATION' as DegreeDto,
    POSTGRADUATED: 'POST_GRADUATED' as DegreeDto,
    MASTERSDEGREE: 'MASTERS_DEGREE' as DegreeDto,
    PHDDEGREE: 'PHD_DEGREE' as DegreeDto,
    POSTDOCTORATE: 'POST_DOCTORATE' as DegreeDto
};
