/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DisabilityDto = 'PHYSICAL' | 'HEARING' | 'VISUAL' | 'MENTAL' | 'INTELLECTUAL';

export const DisabilityDto = {
    PHYSICAL: 'PHYSICAL' as DisabilityDto,
    HEARING: 'HEARING' as DisabilityDto,
    VISUAL: 'VISUAL' as DisabilityDto,
    MENTAL: 'MENTAL' as DisabilityDto,
    INTELLECTUAL: 'INTELLECTUAL' as DisabilityDto
};
