/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.10.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DegreeDto } from './degreeDto';
import { EducationStatusDto } from './educationStatusDto';


export interface EducationSection { 
    /**
     * Data de criação.
     */
    createdAt?: Date;
    /**
     * Identificador do currículo a qual a educação está associada.
     */
    resumeId?: string;
    /**
     * Instituição de ensino.
     */
    school?: string;
    /**
     * ID do registro no sistema legado. Esse atributo não é persistido na base, é utilizado apenas como identificador na integração do registro da g5 para G7.
     */
    g5Id?: string;
    degree?: DegreeDto;
    /**
     * Ano de conclusão.
     */
    conclusionYear?: number;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Curso.
     */
    fieldOfStudy?: string;
    status?: EducationStatusDto;
    /**
     * Data da última alteração.
     */
    updatedAt?: Date;
}
