/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ToneAnalysis } from './toneAnalysis';


export interface EmotionTone { 
    /**
     * Alegria.
     */
    joy?: number;
    /**
     * Tristeza.
     */
    sadness?: number;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Repugnância.
     */
    disgust?: number;
    /**
     * Raiva.
     */
    anger?: number;
    /**
     * Medo.
     */
    fear?: number;
    toneAnalysis?: ToneAnalysis;
}
