/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BigFive } from './bigFive';


export interface Extraversion { 
    /**
     * Faceta de socialização.
     */
    gregariousness?: number;
    /**
     * Valor desta dimensão
     */
    dimensionValue?: number;
    /**
     * Faceta de alegria.
     */
    cheerfulness?: number;
    /**
     * Faceta de busca de emoção.
     */
    excitementSeeking?: number;
    /**
     * Faceta de simpatia.
     */
    friendliness?: number;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Faceta de energia.
     */
    activityLevel?: number;
    /**
     * Faceta de assertividade.
     */
    assertiveness?: number;
    bigFive?: BigFive;
}
