/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type IntegrationStatusDto = 'SUCCESS' | 'ERROR' | 'PENDING' | 'SUCCESS_PERSONNEL_MANAGEMENT' | 'ERRORG7';

export const IntegrationStatusDto = {
    SUCCESS: 'SUCCESS' as IntegrationStatusDto,
    ERROR: 'ERROR' as IntegrationStatusDto,
    PENDING: 'PENDING' as IntegrationStatusDto,
    SUCCESSPERSONNELMANAGEMENT: 'SUCCESS_PERSONNEL_MANAGEMENT' as IntegrationStatusDto,
    ERRORG7: 'ERRORG7' as IntegrationStatusDto
};
