/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type LanguageProficiencyDto = 'BASIC' | 'INTERMEDIATE' | 'ADVANCED' | 'FLUENT';

export const LanguageProficiencyDto = {
    BASIC: 'BASIC' as LanguageProficiencyDto,
    INTERMEDIATE: 'INTERMEDIATE' as LanguageProficiencyDto,
    ADVANCED: 'ADVANCED' as LanguageProficiencyDto,
    FLUENT: 'FLUENT' as LanguageProficiencyDto
};
