/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MaritalStatusDto = 'SINGLE' | 'MARRIED' | 'DIVORCED' | 'WIDOWER' | 'CONCUBINAGE' | 'SEPARATED' | 'STABLE_UNION' | 'OTHER';

export const MaritalStatusDto = {
    SINGLE: 'SINGLE' as MaritalStatusDto,
    MARRIED: 'MARRIED' as MaritalStatusDto,
    DIVORCED: 'DIVORCED' as MaritalStatusDto,
    WIDOWER: 'WIDOWER' as MaritalStatusDto,
    CONCUBINAGE: 'CONCUBINAGE' as MaritalStatusDto,
    SEPARATED: 'SEPARATED' as MaritalStatusDto,
    STABLEUNION: 'STABLE_UNION' as MaritalStatusDto,
    OTHER: 'OTHER' as MaritalStatusDto
};
