/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.10.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelStageTypeDto } from './modelStageTypeDto';
import { RecruitmentProcessStage } from './recruitmentProcessStage';


export interface ModelStage { 
    /**
     * Sequência da etapa
     */
    sequence?: number;
    /**
     * Indica se a etapa é de exame médico.
     */
    medicalExam?: boolean;
    recruitmentProcessStage?: RecruitmentProcessStage;
    /**
     * Identificador único do modelo a qual está etapa pertence.
     */
    modelId?: string;
    /**
     * Nome da etapa.
     */
    name?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    type?: ModelStageTypeDto;
}
