/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ModelStageTypeDto = 'HR' | 'REQUESTER' | 'BOTH';

export const ModelStageTypeDto = {
    HR: 'HR' as ModelStageTypeDto,
    REQUESTER: 'REQUESTER' as ModelStageTypeDto,
    BOTH: 'BOTH' as ModelStageTypeDto
};
