/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.10.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PersonalityModelCandidate } from './personalityModelCandidate';


export interface Needs { 
    /**
     * Amor.
     */
    love?: number;
    /**
     * Harmonia.
     */
    harmony?: number;
    /**
     * Ideal.
     */
    ideal?: number;
    /**
     * Curiosidade.
     */
    curiosity?: number;
    /**
     * Retraimento.
     */
    closeness?: number;
    /**
     * Empolgação.
     */
    excitement?: number;
    /**
     * Estrutura.
     */
    structure?: number;
    /**
     * Natureza prática.
     */
    practicality?: number;
    personalityModelCandidate?: PersonalityModelCandidate;
    /**
     * Liberdade.
     */
    liberty?: number;
    /**
     * Expressão da própria personalidade.
     */
    selfExpression?: number;
    /**
     * Desafio.
     */
    challenge?: number;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Estabilidade.
     */
    stability?: number;
}
