/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BigFive } from './bigFive';


export interface Neuroticism { 
    /**
     * Faceta de ansiedade.
     */
    anxiety?: number;
    /**
     * Faceta de autoconsciência.
     */
    selfConsciousness?: number;
    /**
     * Valor desta dimensão
     */
    dimensionValue?: number;
    /**
     * Faceta de auto-indulgência.
     */
    immoderation?: number;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Faceta de depressão.
     */
    depression?: number;
    /**
     * Faceta de resiliência.
     */
    vulnerability?: number;
    /**
     * Faceta de raiva.
     */
    anger?: number;
    bigFive?: BigFive;
}
