/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PersonalityModelVacancy } from './personalityModelVacancy';
import { Question } from './question';


export interface PersonalityQuiz { 
    /**
     * Quantidade de palavras na resposta.
     */
    wordCount?: number;
    /**
     * Indica se o usuário pode alterar o questionário vigente. O usuário só poderá editar, caso nenhum candidato interno ou externo tenha o respondido.
     */
    canEdit?: boolean;
    /**
     * Perguntas do questionário.
     */
    questions?: Array<Question>;
    /**
     * Descrição do questionário.
     */
    description?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Indica se é o modelo vigente (última data de criação - initialDate).
     */
    isActive?: boolean;
    /**
     * Data de início do período de vigência.
     */
    initialDate?: string;
    personalityModelVacancy?: PersonalityModelVacancy;
}
