/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Answer } from './answer';
import { BigFive } from './bigFive';
import { Needs } from './needs';
import { PersonalityQuiz } from './personalityQuiz';
import { ToneAnalysis } from './toneAnalysis';
import { Values } from './values';


export interface PersonalityModelCandidate { 
    needs?: Needs;
    /**
     * ID do candidato externo (quando aplicável).
     */
    resumeId?: string;
    values?: Values;
    /**
     * Repostas do candidato para a criação do modelo e personalidade.
     */
    answers?: Array<Answer>;
    personalityQuiz?: PersonalityQuiz;
    /**
     * ID do candidato interno (quando aplicável).
     */
    employeeId?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    bigFive?: BigFive;
    toneAnalysis?: ToneAnalysis;
}
