/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PersonalInterestSection { 
    /**
     * Data de criação.
     */
    createdAt?: Date;
    /**
     * Identificador do currículo a qual o interesse está associado.
     */
    resumeId?: string;
    /**
     * Interesse.
     */
    interest?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Data da última alteração.
     */
    updatedAt?: Date;
}
