/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Person { 
    /**
     * Link foto miniatura.
     */
    photoThumbnailLink?: string;
    /**
     * Nome completo da pessoa.
     */
    fullName?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Link foto.
     */
    photoLink?: string;
    /**
     * Nome de usuário da pessoa.
     */
    username?: string;
}
