/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.10.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ProcessTypeDto = 'STAFF_INCREASE' | 'REPLACEMENT';

export const ProcessTypeDto = {
    STAFFINCREASE: 'STAFF_INCREASE' as ProcessTypeDto,
    REPLACEMENT: 'REPLACEMENT' as ProcessTypeDto
};
