/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProfessionalExperienceSection { 
    /**
     * Data de criação.
     */
    createdAt?: Date;
    /**
     * Endereço.
     */
    address?: string;
    /**
     * Identificador do currículo a qual o interesse está associado.
     */
    resumeId?: string;
    /**
     * Data final.
     */
    endDate?: string;
    /**
     * ID do registro no sistema legado. Esse atributo não é persistido na base, é utilizado apenas como identificador na integração do registro da g5 para G7.
     */
    g5Id?: string;
    /**
     * Descrição.
     */
    description?: string;
    /**
     * Empresa.
     */
    company?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Cargo.
     */
    position?: string;
    /**
     * Data inicial.
     */
    startDate?: string;
    /**
     * Data da última alteração.
     */
    updatedAt?: Date;
}
