/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.10.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Answer } from './answer';


export interface Question { 
    /**
     * Numero de Ordenação da questão
     */
    orderNumber?: number;
    answer?: Answer;
    /**
     * Descrição da pergunta.
     */
    description?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Questionário utilizado para identificar a personalidade de um candidato.
     */
    personalityQuizId?: string;
    /**
     * Tipo do Registro
     */
    questionType?: string;
}
