/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type RecruitmentProcessStatusDto = 'SUBSCRIBED' | 'SELECTED' | 'DELETED' | 'DISAPPROVED' | 'GIVENUP';

export const RecruitmentProcessStatusDto = {
    SUBSCRIBED: 'SUBSCRIBED' as RecruitmentProcessStatusDto,
    SELECTED: 'SELECTED' as RecruitmentProcessStatusDto,
    DELETED: 'DELETED' as RecruitmentProcessStatusDto,
    DISAPPROVED: 'DISAPPROVED' as RecruitmentProcessStatusDto,
    GIVENUP: 'GIVENUP' as RecruitmentProcessStatusDto
};
