/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ResumeGenderDto = 'MALE' | 'FEMALE' | 'LGPD_EXCLUSION';

export const ResumeGenderDto = {
    MALE: 'MALE' as ResumeGenderDto,
    FEMALE: 'FEMALE' as ResumeGenderDto,
    LGPDEXCLUSION: 'LGPD_EXCLUSION' as ResumeGenderDto
};
