/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ShiftDto = 'FIRST_TURN' | 'SECOND_TURN' | 'THIRD_TURN' | 'FOURTH_TURN' | 'MIST' | 'GENERAL';

export const ShiftDto = {
    FIRSTTURN: 'FIRST_TURN' as ShiftDto,
    SECONDTURN: 'SECOND_TURN' as ShiftDto,
    THIRDTURN: 'THIRD_TURN' as ShiftDto,
    FOURTHTURN: 'FOURTH_TURN' as ShiftDto,
    MIST: 'MIST' as ShiftDto,
    GENERAL: 'GENERAL' as ShiftDto
};
