/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type StaffRequisitionStatusDto = 'IN_DEFINITION' | 'IN_APPROVAL' | 'APPROVED' | 'REJECTED' | 'CANCELED';

export const StaffRequisitionStatusDto = {
    INDEFINITION: 'IN_DEFINITION' as StaffRequisitionStatusDto,
    INAPPROVAL: 'IN_APPROVAL' as StaffRequisitionStatusDto,
    APPROVED: 'APPROVED' as StaffRequisitionStatusDto,
    REJECTED: 'REJECTED' as StaffRequisitionStatusDto,
    CANCELED: 'CANCELED' as StaffRequisitionStatusDto
};
