/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 15.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type VacancyAdmissionSituationDto = 'PENDING' | 'CONCLUDED';

export const VacancyAdmissionSituationDto = {
    PENDING: 'PENDING' as VacancyAdmissionSituationDto,
    CONCLUDED: 'CONCLUDED' as VacancyAdmissionSituationDto
};
