/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShiftDto } from './shiftDto';


export interface WorkShift { 
    /**
     * Código do turno de trabalho.
     */
    code?: number;
    shift?: ShiftDto;
    /**
     * Descrição do turno.
     */
    description?: string;
    /**
     * Identificador do turno de trabalho.
     */
    id?: string;
}
