/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { CostCenter } from './costCenter';
import { Department } from './department';
import { JobPosition } from './jobPosition';


export interface WorkstationGroup { 
    branchOffice?: Company;
    /**
     * Código do posto.
     */
    code?: string;
    /**
     * Centro de custo que compõe o grupo de posto de trabalho.
     */
    costCenterId?: string;
    /**
     * Identificador da matriz do posto de trabalho.
     */
    headOfficeId?: string;
    costCenter?: CostCenter;
    /**
     * Nome do grupo de postos de trabalho.
     */
    name?: string;
    /**
     * Lista de postos de trabalho.
     */
    jobPositions?: Array<JobPosition>;
    /**
     * Identificador único que representa o posto de trabalho.
     */
    id?: string;
    /**
     * Identificador da filial do posto de trabalho.
     */
    branchOfficeId?: string;
    department?: Department;
    /**
     * Identificador do departamento a qual o grupo de postos de trabalho está associado.
     */
    departamentId?: string;
}
