/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountType } from './accountType';
import { Bank } from './bank';
import { BankBranch } from './bankBranch';


export interface Account { 
    /**
     * Conta bancária
     */
    bankAccount: string;
    bankBranchId: BankBranch;
    bankId: Bank;
    accountType: AccountType;
    /**
     * Id da funcionário
     */
    employeeId: string;
    /**
     * Id da conta bancária
     */
    id?: string;
    /**
     * Digito da conta
     */
    digit: string;
}
