/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type AccountType = 'CurrentAccount' | 'SavingsAccount' | 'SalaryAccount' | 'Others';

export const AccountType = {
    CurrentAccount: 'CurrentAccount' as AccountType,
    SavingsAccount: 'SavingsAccount' as AccountType,
    SalaryAccount: 'SalaryAccount' as AccountType,
    Others: 'Others' as AccountType
};
