/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalPaymentType } from './additionalPaymentType';
import { JobActingType } from './jobActingType';


export interface Actingtype { 
    /**
     * Código do tipo de atuação
     */
    code?: number;
    /**
     * Objetivo
     */
    goal?: string;
    additionalPaymentType?: AdditionalPaymentType;
    /**
     * Porcentagem do pagamento do posto adicional
     */
    additionalPaymentPercentage?: number;
    /**
     * Descrição do tipo de atuação
     */
    name?: string;
    /**
     * Consistir característica?
     */
    consistCharacteristic?: boolean;
    jobActingType?: JobActingType;
    /**
     * Id do tipo de atuação
     */
    id?: string;
    /**
     * Histórico principal?
     */
    mainhistory?: boolean;
}
