/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type AdditionalPaymentType = 'TYPE_0' | 'TYPE_1' | 'TYPE_2' | 'TYPE_3' | 'TYPE_4' | 'TYPE_5' | 'TYPE_6' | 'TYPE_7' | 'TYPE_8' | 'TYPE_9';

export const AdditionalPaymentType = {
    _0: 'TYPE_0' as AdditionalPaymentType,
    _1: 'TYPE_1' as AdditionalPaymentType,
    _2: 'TYPE_2' as AdditionalPaymentType,
    _3: 'TYPE_3' as AdditionalPaymentType,
    _4: 'TYPE_4' as AdditionalPaymentType,
    _5: 'TYPE_5' as AdditionalPaymentType,
    _6: 'TYPE_6' as AdditionalPaymentType,
    _7: 'TYPE_7' as AdditionalPaymentType,
    _8: 'TYPE_8' as AdditionalPaymentType,
    _9: 'TYPE_9' as AdditionalPaymentType
};
