/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from './addressType';
import { Administrativeregion } from './administrativeregion';
import { City } from './city';
import { Neighborhood } from './neighborhood';


export interface Address { 
    neighborhoodId?: Neighborhood;
    /**
     * Número do endereço
     */
    number?: string;
    /**
     * Endereço
     */
    address?: string;
    /**
     * Data de alteração do endereço
     */
    updatedate?: string;
    /**
     * Código de endereçamento postal
     */
    postalcode?: string;
    /**
     * Informação adicional referente ao endereço
     */
    additional?: string;
    administrativeregion?: Administrativeregion;
    addresstype?: AddressType;
    /**
     * Id do endereço
     */
    id?: string;
    cityId?: City;
    /**
     * Bairro/Distrito a qual pertence este endereço, legado usado no hcm
     */
    neighborhood?: string;
}
