/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ApportionmentDiscountType = 'TYPE_1' | 'TYPE_2';

export const ApportionmentDiscountType = {
    _1: 'TYPE_1' as ApportionmentDiscountType,
    _2: 'TYPE_2' as ApportionmentDiscountType
};
