/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ApportionmentUseType = 'DONT_USE_APPORTIONMENT' | 'APPORTIONMENT_BY_DEPARTMENT' | 'APPORTIONMENT_BY_COST_CENTER';

export const ApportionmentUseType = {
  DONTUSEAPPORTIONMENT: 'DONT_USE_APPORTIONMENT' as ApportionmentUseType,
  APPORTIONMENTBYDEPARTMENT: 'APPORTIONMENT_BY_DEPARTMENT' as ApportionmentUseType,
  APPORTIONMENTBYCOSTCENTER: 'APPORTIONMENT_BY_COST_CENTER' as ApportionmentUseType
};
