/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttendantType } from './attendantType';
import { Employee } from './employee';
import { Phonecontact } from './phonecontact';
import { Professionalcouncil } from './professionalcouncil';


export interface Attendant { 
    /**
     * Situação do registro
     */
    situationCouncil?: string;
    /**
     * Código do atendente
     */
    code?: number;
    phoneContact?: Phonecontact;
    /**
     * Registro profissional
     */
    recordCouncil?: string;
    /**
     * Nome do atendente
     */
    name?: string;
    /**
     * Id do atendente
     */
    id?: string;
    employee?: Employee;
    professionalCouncil?: Professionalcouncil;
    attendantType?: AttendantType;
}
