/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CalculationAveragePriorNoticeType = 'CLT' | 'AGREED';

export const CalculationAveragePriorNoticeType = {
    CLT: 'CLT' as CalculationAveragePriorNoticeType,
    AGREED: 'AGREED' as CalculationAveragePriorNoticeType
};
