/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CivilCertificateType = 'BIRTH_CERTIFICATE' | 'MARRIAGE_CERTIFICATE' | 'INDIGENOUS_PERSONS_BIRTH_CERTIFICATE' | 'DEATH_CERTIFICATE';

export const CivilCertificateType = {
  BIRTHCERTIFICATE: 'BIRTH_CERTIFICATE' as CivilCertificateType,
  MARRIAGECERTIFICATE: 'MARRIAGE_CERTIFICATE' as CivilCertificateType,
  INDIGENOUSPERSONSBIRTHCERTIFICATE: 'INDIGENOUS_PERSONS_BIRTH_CERTIFICATE' as CivilCertificateType,
  DEATHCERTIFICATE: 'DEATH_CERTIFICATE' as CivilCertificateType
};
