/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ClassOrganType = 'CRM' | 'RMS' | 'CRO';

export const ClassOrganType = {
    CRM: 'CRM' as ClassOrganType,
    RMS: 'RMS' as ClassOrganType,
    CRO: 'CRO' as ClassOrganType
};
