/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CompanyType = 'BRANCH_OFFICE' | 'HEAD_OFFICE' | 'WORK' | 'TEMPORARY' | 'WORK_COOPERATIVELY' | 'DOMESTIC_WORKER' | 'EMPLOYER_ESOCIAL';

export const CompanyType = {
  BRANCHOFFICE: 'BRANCH_OFFICE' as CompanyType,
  HEADOFFICE: 'HEAD_OFFICE' as CompanyType,
  WORK: 'WORK' as CompanyType,
  TEMPORARY: 'TEMPORARY' as CompanyType,
  WORKCOOPERATIVELY: 'WORK_COOPERATIVELY' as CompanyType,
  DOMESTICWORKER: 'DOMESTIC_WORKER' as CompanyType,
  EMPLOYERESOCIAL: 'EMPLOYER_ESOCIAL' as CompanyType
};
