/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ApportionmentDiscountType } from './apportionmentDiscountType';
import { ApportionmentUseType } from './apportionmentUseType';
import { CompanyType } from './companyType';
import { SubscriptionType } from './subscriptionType';
import { TakersRoutineUseType } from './takersRoutineUseType';


export interface Company { 
    /**
     * Código da empresa
     */
    code?: number;
    /**
     * Cnpj da empresa
     */
    cnpj?: string;
    /**
     * Usa histórico pensão judicial
     */
    useJudicialPensionHistory?: boolean;
    apportionmentUseType?: ApportionmentUseType;
    takersRoutineUseType?: TakersRoutineUseType;
    apportionmentDiscountType?: ApportionmentDiscountType;
    subscriptionType?: SubscriptionType;
    /**
     * Relacionamento com a sede da empresa
     */
    headquarter?: string;
    /**
     * Nome da empresa
     */
    companyname?: string;
    companytype?: CompanyType;
    /**
     * Início rotina tomadores por rateio
     */
    takersRoutineStartDate?: string;
    /**
     * Nome fantasia da empresa
     */
    tradingname?: string;
    /**
     * Id da empresa
     */
    id?: string;
    place?: Address;
}
