/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CurrencyType = 'Real' | 'Dolar' | 'Index';

export const CurrencyType = {
    Real: 'Real' as CurrencyType,
    Dolar: 'Dolar' as CurrencyType,
    Index: 'Index' as CurrencyType
};
