/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DecisionPcD = 'No' | 'Also' | 'Only';

export const DecisionPcD = {
    No: 'No' as DecisionPcD,
    Also: 'Also' as DecisionPcD,
    Only: 'Only' as DecisionPcD
};
