/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Apportionment } from './apportionment';


export interface Department { 
    /**
     * Id da tabela de feriados noturnos
     */
    nightTimeHoliday?: string;
    /**
     * Data de criação
     */
    creationdate: string;
    /**
     * Código do local
     */
    code: string;
    /**
     * Nome do local
     */
    name: string;
    /**
     * Id da tabela de feriados diurnos
     */
    daytimeHoliday?: string;
    apportionment?: Apportionment;
    /**
     * Id de sistema externo
     */
    externalId?: string;
    /**
     * Id do local
     */
    id?: string;
    /**
     * Posição
     */
    position: string;
    /**
     * Código da tabela
     */
    tablecode: number;
    /**
     * Data de extinção
     */
    expirationdate: string;
}
