/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Disease { 
    /**
     * Código da Doença
     */
    code: string;
    /**
     * Descrição da doença
     */
    name: string;
    /**
     * Identificador
     */
    id?: string;
}
