/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DocumentType = 'VOTER_REGISTRATION_CARD' | 'DRIVERS_LICENSE' | 'RESERVIST_CERTIFICATE' | 'CIVIL_CERTIFICATE' | 'PASSPORT' | 'CIVILIAN_IDENTITY_REGISTRY' | 'NATURALIZATION_DECREE' | 'NATIONAL_HEALTH_CARD' | 'DECLARATION_OF_LIVE_BIRTH' | 'PROFESSIONAL_COUNCIL' | 'RG' | 'CPF' | 'DEATH_CERTIFICATE' | 'PROVISION_FUND' | 'SOCIAL_INSURANCE' | 'IDENTIFICATION_DOCUMENT';

export const DocumentType = {
    VOTERREGISTRATIONCARD: 'VOTER_REGISTRATION_CARD' as DocumentType,
    DRIVERSLICENSE: 'DRIVERS_LICENSE' as DocumentType,
    RESERVISTCERTIFICATE: 'RESERVIST_CERTIFICATE' as DocumentType,
    CIVILCERTIFICATE: 'CIVIL_CERTIFICATE' as DocumentType,
    PASSPORT: 'PASSPORT' as DocumentType,
    CIVILIANIDENTITYREGISTRY: 'CIVILIAN_IDENTITY_REGISTRY' as DocumentType,
    NATURALIZATIONDECREE: 'NATURALIZATION_DECREE' as DocumentType,
    NATIONALHEALTHCARD: 'NATIONAL_HEALTH_CARD' as DocumentType,
    DECLARATIONOFLIVEBIRTH: 'DECLARATION_OF_LIVE_BIRTH' as DocumentType,
    PROFESSIONALCOUNCIL: 'PROFESSIONAL_COUNCIL' as DocumentType,
    RG: 'RG' as DocumentType,
    CPF: 'CPF' as DocumentType,
    DEATHCERTIFICATE: 'DEATH_CERTIFICATE' as DocumentType,
    PROVISIONFUND: 'PROVISION_FUND' as DocumentType,
    SOCIALINSURANCE: 'SOCIAL_INSURANCE' as DocumentType,
    IDENTIFICATIONDOCUMENT: 'IDENTIFICATION_DOCUMENT' as DocumentType
};
