/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { City } from './city';
import { CivilCertificateType } from './civilCertificateType';
import { Country } from './country';
import { Dependent } from './dependent';
import { DocumentType } from './documentType';
import { Person } from './person';
import { ProfessionalCouncilSituationType } from './professionalCouncilSituationType';
import { Professionalcouncil } from './professionalcouncil';
import { State } from './state';


export interface Document { 
    issuerState?: State;
    documentType?: DocumentType;
    /**
     * Número do documento
     */
    documentNumber?: string;
    /**
     * Termo da certidão de nascimento
     */
    termOfCivilCertificate?: string;
    /**
     * Registro profissional
     */
    professionalRegistry?: string;
    /**
     * Orgão emissor
     */
    issuer?: string;
    /**
     * Folha da certidão de nascimento
     */
    pageOfCivilCertificate?: string;
    /**
     * Zona eleitoral
     */
    votingDistrict?: string;
    /**
     * Data da expedição do conselho profissional
     */
    professionalCouncilExpeditionDate?: string;
    /**
     * Id do documento
     */
    id?: string;
    /**
     * Série do título de eleitor
     */
    serialOfVoterRegistrationCard?: string;
    /**
     * Livro da certidão de nascimento
     */
    bookOfCivilCertificate?: string;
    professionalCouncil?: Professionalcouncil;
    dependent?: Dependent;
    /**
     * Data de validade
     */
    expirationDate?: string;
    /**
     * Registro do conselho
     */
    councilRegistry?: string;
    /**
     * Data da expedição
     */
    dateOfIssue?: string;
    issuerCountry?: Country;
    professionalCouncilSituation?: ProfessionalCouncilSituationType;
    /**
     * Data de validade do conselho profissional
     */
    professionalCouncilExpirationDate?: string;
    /**
     * Data da primeira habilitação
     */
    firstDriverLicenceDate?: string;
    /**
     * Portaria de naturalização
     */
    naturalizationDecree?: string;
    person?: Person;
    issuerCity?: City;
    /**
     * Cartório da certidão de nascimento
     */
    notaryOffice?: string;
    /**
     * Categoria
     */
    category?: string;
    civilCertificate?: CivilCertificateType;
}
