/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EmailType = 'Personal' | 'Professional';

export const EmailType = {
    Personal: 'Personal' as EmailType,
    Professional: 'Professional' as EmailType
};
