/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentRelationship } from './paymentRelationship';
import { RaisType } from './raisType';


export interface EmploymentRelationship { 
    /**
     * Código do vínculo
     */
    code?: number;
    /**
     * Descrição do vínculo
     */
    name: string;
    /**
     * Id do vínculo
     */
    id?: string;
    rais: RaisType;
    paymentRelationship?: PaymentRelationship;
}
