/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ESocialCategory = 'Category_101' | 'Category_102' | 'Category_103' | 'Category_104' | 'Category_105' | 'Category_106' | 'Category_111' | 'Category_201' | 'Category_202' | 'Category_301' | 'Category_302' | 'Category_303' | 'Category_305' | 'Category_306' | 'Category_307' | 'Category_308' | 'Category_309' | 'Category_401' | 'Category_410' | 'Category_701' | 'Category_711' | 'Category_712' | 'Category_721' | 'Category_722' | 'Category_723' | 'Category_731' | 'Category_734' | 'Category_738' | 'Category_741' | 'Category_751' | 'Category_761' | 'Category_771' | 'Category_781' | 'Category_901' | 'Category_902' | 'Category_903' | 'Category_904' | 'Category_905' | 'Category_997' | 'Category_998' | 'Category_999';

export const ESocialCategory = {
    _101: 'Category_101' as ESocialCategory,
    _102: 'Category_102' as ESocialCategory,
    _103: 'Category_103' as ESocialCategory,
    _104: 'Category_104' as ESocialCategory,
    _105: 'Category_105' as ESocialCategory,
    _106: 'Category_106' as ESocialCategory,
    _111: 'Category_111' as ESocialCategory,
    _201: 'Category_201' as ESocialCategory,
    _202: 'Category_202' as ESocialCategory,
    _301: 'Category_301' as ESocialCategory,
    _302: 'Category_302' as ESocialCategory,
    _303: 'Category_303' as ESocialCategory,
    _305: 'Category_305' as ESocialCategory,
    _306: 'Category_306' as ESocialCategory,
    _307: 'Category_307' as ESocialCategory,
    _308: 'Category_308' as ESocialCategory,
    _309: 'Category_309' as ESocialCategory,
    _401: 'Category_401' as ESocialCategory,
    _410: 'Category_410' as ESocialCategory,
    _701: 'Category_701' as ESocialCategory,
    _711: 'Category_711' as ESocialCategory,
    _712: 'Category_712' as ESocialCategory,
    _721: 'Category_721' as ESocialCategory,
    _722: 'Category_722' as ESocialCategory,
    _723: 'Category_723' as ESocialCategory,
    _731: 'Category_731' as ESocialCategory,
    _734: 'Category_734' as ESocialCategory,
    _738: 'Category_738' as ESocialCategory,
    _741: 'Category_741' as ESocialCategory,
    _751: 'Category_751' as ESocialCategory,
    _761: 'Category_761' as ESocialCategory,
    _771: 'Category_771' as ESocialCategory,
    _781: 'Category_781' as ESocialCategory,
    _901: 'Category_901' as ESocialCategory,
    _902: 'Category_902' as ESocialCategory,
    _903: 'Category_903' as ESocialCategory,
    _904: 'Category_904' as ESocialCategory,
    _905: 'Category_905' as ESocialCategory,
    _997: 'Category_997' as ESocialCategory,
    _998: 'Category_998' as ESocialCategory,
    _999: 'Category_999' as ESocialCategory
};
