/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type FormDisregardWithdrawalDayType = 'NOT_CONSIDERED' | 'YEAR_CALCULATION' | 'TOTAL_OF_DAYS_CALCULATION';

export const FormDisregardWithdrawalDayType = {
    NOTCONSIDERED: 'NOT_CONSIDERED' as FormDisregardWithdrawalDayType,
    YEARCALCULATION: 'YEAR_CALCULATION' as FormDisregardWithdrawalDayType,
    TOTALOFDAYSCALCULATION: 'TOTAL_OF_DAYS_CALCULATION' as FormDisregardWithdrawalDayType
};
