/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type GenerateStabilityType = 'NO' | 'INITIAL_LEAVE' | 'FINAL_LEAVE' | 'LEAVE_DAYS';

export const GenerateStabilityType = {
  NO: 'NO' as GenerateStabilityType,
  INITIALLEAVE: 'INITIAL_LEAVE' as GenerateStabilityType,
  FINALLEAVE: 'FINAL_LEAVE' as GenerateStabilityType,
  LEAVEDAYS: 'LEAVE_DAYS' as GenerateStabilityType
};
