/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type HireType = 'Empty' | 'FirstJob' | 'Reemprego' | 'TransferWithOnus' | 'TransferWithoutOnus' | 'Incorporation' | 'Reintegration' | 'Reconstruction' | 'Reversal' | 'Provisional' | 'Request' | 'Redistribution' | 'Decentralized' | 'Removal' | 'Readaptation';

export const HireType = {
    Empty: 'Empty' as HireType,
    FirstJob: 'FirstJob' as HireType,
    Reemprego: 'Reemprego' as HireType,
    TransferWithOnus: 'TransferWithOnus' as HireType,
    TransferWithoutOnus: 'TransferWithoutOnus' as HireType,
    Incorporation: 'Incorporation' as HireType,
    Reintegration: 'Reintegration' as HireType,
    Reconstruction: 'Reconstruction' as HireType,
    Reversal: 'Reversal' as HireType,
    Provisional: 'Provisional' as HireType,
    Request: 'Request' as HireType,
    Redistribution: 'Redistribution' as HireType,
    Decentralized: 'Decentralized' as HireType,
    Removal: 'Removal' as HireType,
    Readaptation: 'Readaptation' as HireType
};
