/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ESocialCategory } from './eSocialCategory';
import { Employee } from './employee';


export interface HistoricalEsocialCategory { 
    /**
     * Data do histórico
     */
    dateWhen?: string;
    /**
     * Data de término
     */
    endDate?: string;
    /**
     * Id do histórico
     */
    id?: string;
    employee?: Employee;
    eSocialCategoryType?: ESocialCategory;
}
