/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { IntervalGroup } from './intervalGroup';
import { ScaleCategory } from './scaleCategory';
import { ScaleTeam } from './scaleTeam';
import { Workshift } from './workshift';
import { WorkshiftGroup } from './workshiftGroup';


export interface HistoricalWorkshift { 
    intervalGroupId?: IntervalGroup;
    /**
     * Lote do histórico de posto de trabalho
     */
    lotWorkstation?: string;
    /**
     * Data do histórico
     */
    dateWhen: string;
    /**
     * Data fim do histórico
     */
    endDate?: string;
    workshiftId: Workshift;
    scaleTeam?: ScaleTeam;
    scaleCategory?: ScaleCategory;
    workshiftGroupId: WorkshiftGroup;
    /**
     * Id do histórico
     */
    id?: string;
    /**
     * É integração? (campo calculado)
     */
    isIntegration?: boolean;
    employee: Employee;
}
