/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Workshift } from './workshift';


export interface IntervalGroup { 
    /**
     * Código da turma
     */
    code?: number;
    workshift?: Workshift;
    /**
     * Descrição da turma
     */
    description?: string;
    /**
     * Id da turma de intervalo
     */
    id?: string;
}
