/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Jobposition { 
    /**
     * CBO do cargo
     */
    cbo?: string;
    /**
     * Código do cargo
     */
    code?: string;
    /**
     * Nome do cargo
     */
    name?: string;
    /**
     * Id da estrutura de cargos
     */
    jobpositionstructure?: string;
    /**
     * Id do cargo
     */
    id?: string;
    /**
     * Data de criação do cargo
     */
    creationDate?: string;
    /**
     * Data de extinção do cargo
     */
    expirationDate?: string;
}
