/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type KinshipDegree = 'Adopted' | 'Child' | 'Concubine' | 'ExSpouse' | 'ExPartner' | 'Grandparent' | 'Grandchild' | 'GreatGrandparent' | 'GreatGrandchild' | 'Guardianship' | 'NephewNiece' | 'Other' | 'Parent' | 'FatherInLaw' | 'Partner' | 'Pensioners' | 'Pupil' | 'Sibling' | 'SonDaughterInLaw' | 'Spouse' | 'Stepfather' | 'Stepmother' | 'Stepchild' | 'Trusted' | 'UncleAunt' | 'Tutor';

export const KinshipDegree = {
    Adopted: 'Adopted' as KinshipDegree,
    Child: 'Child' as KinshipDegree,
    Concubine: 'Concubine' as KinshipDegree,
    ExSpouse: 'ExSpouse' as KinshipDegree,
    ExPartner: 'ExPartner' as KinshipDegree,
    Grandparent: 'Grandparent' as KinshipDegree,
    Grandchild: 'Grandchild' as KinshipDegree,
    GreatGrandparent: 'GreatGrandparent' as KinshipDegree,
    GreatGrandchild: 'GreatGrandchild' as KinshipDegree,
    Guardianship: 'Guardianship' as KinshipDegree,
    NephewNiece: 'NephewNiece' as KinshipDegree,
    Other: 'Other' as KinshipDegree,
    Parent: 'Parent' as KinshipDegree,
    FatherInLaw: 'FatherInLaw' as KinshipDegree,
    Partner: 'Partner' as KinshipDegree,
    Pensioners: 'Pensioners' as KinshipDegree,
    Pupil: 'Pupil' as KinshipDegree,
    Sibling: 'Sibling' as KinshipDegree,
    SonDaughterInLaw: 'SonDaughterInLaw' as KinshipDegree,
    Spouse: 'Spouse' as KinshipDegree,
    Stepfather: 'Stepfather' as KinshipDegree,
    Stepmother: 'Stepmother' as KinshipDegree,
    Stepchild: 'Stepchild' as KinshipDegree,
    Trusted: 'Trusted' as KinshipDegree,
    UncleAunt: 'UncleAunt' as KinshipDegree,
    Tutor: 'Tutor' as KinshipDegree
};
