/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type LoseVacationRightType = 'TYPE_A_LOSE_RIGHT_GREATER_THAN_180_DAYS' | 'TYPE_L_LOSE_RIGHT_GREATER_THAN_30_DAYS' | 'TYPE_I_INTERRUPTS_AND_CONTINUES_ON_RETURN' | 'TYPE_P_LOSE_FRACTION_CORRESPONDING_TO_THE_MONTH' | 'TYPE_N_NOT_CONSIDER_FOR_VACATION_RIGHT_CALCULATION';

export const LoseVacationRightType = {
  ALOSERIGHTGREATERTHAN180DAYS: 'TYPE_A_LOSE_RIGHT_GREATER_THAN_180_DAYS' as LoseVacationRightType,
  LLOSERIGHTGREATERTHAN30DAYS: 'TYPE_L_LOSE_RIGHT_GREATER_THAN_30_DAYS' as LoseVacationRightType,
  IINTERRUPTSANDCONTINUESONRETURN: 'TYPE_I_INTERRUPTS_AND_CONTINUES_ON_RETURN' as LoseVacationRightType,
  PLOSEFRACTIONCORRESPONDINGTOTHEMONTH: 'TYPE_P_LOSE_FRACTION_CORRESPONDING_TO_THE_MONTH' as LoseVacationRightType,
  NNOTCONSIDERFORVACATIONRIGHTCALCULATION: 'TYPE_N_NOT_CONSIDER_FOR_VACATION_RIGHT_CALCULATION' as LoseVacationRightType
};
