/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MaritalStatus = 'Single' | 'Married' | 'Divorced' | 'Widower' | 'Concubinage' | 'Separated' | 'StableUnion' | 'Others';

export const MaritalStatus = {
    Single: 'Single' as MaritalStatus,
    Married: 'Married' as MaritalStatus,
    Divorced: 'Divorced' as MaritalStatus,
    Widower: 'Widower' as MaritalStatus,
    Concubinage: 'Concubinage' as MaritalStatus,
    Separated: 'Separated' as MaritalStatus,
    StableUnion: 'StableUnion' as MaritalStatus,
    Others: 'Others' as MaritalStatus
};
