/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MovimentationRaisType = 'TYPE_10' | 'TYPE_20' | 'TYPE_30' | 'TYPE_40' | 'TYPE_50' | 'TYPE_60' | 'TYPE_70';

export const MovimentationRaisType = {
    _10: 'TYPE_10' as MovimentationRaisType,
    _20: 'TYPE_20' as MovimentationRaisType,
    _30: 'TYPE_30' as MovimentationRaisType,
    _40: 'TYPE_40' as MovimentationRaisType,
    _50: 'TYPE_50' as MovimentationRaisType,
    _60: 'TYPE_60' as MovimentationRaisType,
    _70: 'TYPE_70' as MovimentationRaisType
};
