/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MovimentationReasonType } from './movimentationReasonType';


export interface Movimentationreason { 
    /**
     * Código do motivo
     */
    code: number;
    /**
     * Nome do motivo
     */
    name: string;
    /**
     * Id do motivo
     */
    id?: string;
    movimentationReasonType?: MovimentationReasonType;
}
