/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NationalityType } from './nationalityType';


export interface Nationality { 
    /**
     * Código da nacionalidade
     */
    code?: number;
    nationalityType?: NationalityType;
    /**
     * Nome da nacionalidade
     */
    name?: string;
    /**
     * Id da nacionalidade
     */
    id?: string;
}
