/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type NationalityType = 'BRAZILIAN' | 'NATURALIZED_BRAZILIAN' | 'ARGENTINE' | 'BOLIVIAN' | 'CHILEAN' | 'PARAGUAYAN' | 'URUGUAYAN' | 'VENEZULAN' | 'COLOMBIAN' | 'PERUVIAN' | 'EQUATORIAN' | 'GERMAN' | 'BELGIAN' | 'BRITISH' | 'CANADIAN' | 'SPANISH' | 'NORTH_AMERICAN' | 'FRENCH' | 'SWISS' | 'ITALIAN' | 'HAITIAN' | 'JAPANESE' | 'CHINESE' | 'KOREAN' | 'RUSSIAN' | 'PORTUGUESE' | 'SWENDISH' | 'FINNISH' | 'OTHER_LATIN_AMERICANS' | 'OTHER_ASIANS' | 'ENGALIAN' | 'OTHER_EUROPEAN' | 'ANGOLAN' | 'CONGOLES' | 'SOUTH_AFRICAN' | 'PAKISTANI' | 'INDIAN' | 'GANES' | 'SENEGALESE' | 'OTHER_AMERICANS' | 'OTHERS';

export const NationalityType = {
  BRAZILIAN: 'BRAZILIAN' as NationalityType,
  NATURALIZEDBRAZILIAN: 'NATURALIZED_BRAZILIAN' as NationalityType,
  ARGENTINE: 'ARGENTINE' as NationalityType,
  BOLIVIAN: 'BOLIVIAN' as NationalityType,
  CHILEAN: 'CHILEAN' as NationalityType,
  PARAGUAYAN: 'PARAGUAYAN' as NationalityType,
  URUGUAYAN: 'URUGUAYAN' as NationalityType,
  VENEZULAN: 'VENEZULAN' as NationalityType,
  COLOMBIAN: 'COLOMBIAN' as NationalityType,
  PERUVIAN: 'PERUVIAN' as NationalityType,
  EQUATORIAN: 'EQUATORIAN' as NationalityType,
  GERMAN: 'GERMAN' as NationalityType,
  BELGIAN: 'BELGIAN' as NationalityType,
  BRITISH: 'BRITISH' as NationalityType,
  CANADIAN: 'CANADIAN' as NationalityType,
  SPANISH: 'SPANISH' as NationalityType,
  NORTHAMERICAN: 'NORTH_AMERICAN' as NationalityType,
  FRENCH: 'FRENCH' as NationalityType,
  SWISS: 'SWISS' as NationalityType,
  ITALIAN: 'ITALIAN' as NationalityType,
  HAITIAN: 'HAITIAN' as NationalityType,
  JAPANESE: 'JAPANESE' as NationalityType,
  CHINESE: 'CHINESE' as NationalityType,
  KOREAN: 'KOREAN' as NationalityType,
  RUSSIAN: 'RUSSIAN' as NationalityType,
  PORTUGUESE: 'PORTUGUESE' as NationalityType,
  SWENDISH: 'SWENDISH' as NationalityType,
  FINNISH: 'FINNISH' as NationalityType,
  OTHERLATINAMERICANS: 'OTHER_LATIN_AMERICANS' as NationalityType,
  OTHERASIANS: 'OTHER_ASIANS' as NationalityType,
  ENGALIAN: 'ENGALIAN' as NationalityType,
  OTHEREUROPEAN: 'OTHER_EUROPEAN' as NationalityType,
  ANGOLAN: 'ANGOLAN' as NationalityType,
  CONGOLES: 'CONGOLES' as NationalityType,
  SOUTHAFRICAN: 'SOUTH_AFRICAN' as NationalityType,
  PAKISTANI: 'PAKISTANI' as NationalityType,
  INDIAN: 'INDIAN' as NationalityType,
  GANES: 'GANES' as NationalityType,
  SENEGALESE: 'SENEGALESE' as NationalityType,
  OTHERAMERICANS: 'OTHER_AMERICANS' as NationalityType,
  OTHERS: 'OTHERS' as NationalityType
};
