/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Administrativeregion } from './administrativeregion';
import { City } from './city';


export interface Neighborhood { 
    /**
     * Código do bairro
     */
    code?: number;
    city?: City;
    /**
     * Nome do bairro
     */
    name?: string;
    /**
     * Id do bairro
     */
    id?: string;
    administrativeRegion?: Administrativeregion;
    /**
     * CEP
     */
    cep?: string;
}
