/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OriginExpenseNatureType = 'TYPED' | 'GENERATED_BY_JOB_POSITION' | 'GENERATED_BY_WORKSTATION';

export const OriginExpenseNatureType = {
    TYPED: 'TYPED' as OriginExpenseNatureType,
    GENERATEDBYJOBPOSITION: 'GENERATED_BY_JOB_POSITION' as OriginExpenseNatureType,
    GENERATEDBYWORKSTATION: 'GENERATED_BY_WORKSTATION' as OriginExpenseNatureType
};
