/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OtherContractType = 'SINGLE_CONTRACT' | 'OTHER_CONTRACT_OFF_SYSTEM' | 'OTHER_CONTRACT_WITHIN_SYSTEM' | 'CONTRACT_OUT_SAME_CPF';

export const OtherContractType = {
  SINGLECONTRACT: 'SINGLE_CONTRACT' as OtherContractType,
  OTHERCONTRACTOFFSYSTEM: 'OTHER_CONTRACT_OFF_SYSTEM' as OtherContractType,
  OTHERCONTRACTWITHINSYSTEM: 'OTHER_CONTRACT_WITHIN_SYSTEM' as OtherContractType,
  CONTRACTOUTSAMECPF: 'CONTRACT_OUT_SAME_CPF' as OtherContractType
};
