/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmploymentRelationship } from './employmentRelationship';


export interface PaymentRelationship { 
    employmentRelationship?: EmploymentRelationship;
    /**
     * Indicar se o vínculo refere-se a um regime de teletrabalho
     */
    homeOffice?: boolean;
    /**
     * Id dos pagamentos
     */
    id?: string;
}
