/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { City } from './city';
import { GenderType } from './genderType';
import { MaritalStatus } from './maritalStatus';
import { Nationality } from './nationality';
import { Professionalcouncil } from './professionalcouncil';
import { RacialType } from './racialType';
import { Religion } from './religion';


export interface Person { 
    /**
     * Data de aniversário
     */
    birthday?: string;
    /**
     * Nome do pai
     */
    fatherName?: string;
    /**
     * Primeiro nome
     */
    firstname: string;
    race: RacialType;
    gender: GenderType;
    /**
     * É uma pessoa com deficiência?
     */
    isdisabledperson: boolean;
    /**
     * Nome da mãe
     */
    motherName?: string;
    /**
     * Nome do meio
     */
    middlename?: string;
    /**
     * Relacionamento com grau de instrução
     */
    educationdegree: string;
    placeofbirth?: City;
    /**
     * Último nome
     */
    lastname: string;
    religion?: Religion;
    /**
     * Nome social
     */
    socialName?: string;
    nationality: Nationality;
    /**
     * Id do upload da foto da g7
     */
    attachment?: string;
    maritalstatus?: MaritalStatus;
    /**
     * Número de CPF
     */
    cpf?: string;
    /**
     * Apelido
     */
    nickname?: string;
    /**
     * Id da pessoa
     */
    id?: string;
    professionalCouncil?: Professionalcouncil;
    /**
     * Nome de usuário
     */
    username?: string;
}
