/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PhoneContactType = 'Personal' | 'Professional' | 'Mobile' | 'BusinessFax' | 'PersonalFax' | 'Other';

export const PhoneContactType = {
    Personal: 'Personal' as PhoneContactType,
    Professional: 'Professional' as PhoneContactType,
    Mobile: 'Mobile' as PhoneContactType,
    BusinessFax: 'BusinessFax' as PhoneContactType,
    PersonalFax: 'PersonalFax' as PhoneContactType,
    Other: 'Other' as PhoneContactType
};
