/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CalculationAveragePriorNoticeType } from './calculationAveragePriorNoticeType';
import { DaysAdditionInCountType } from './daysAdditionInCountType';
import { FormAdditionCountType } from './formAdditionCountType';
import { FormDisregardWithdrawalDayType } from './formDisregardWithdrawalDayType';
import { PriorNoticeDaysInCountType } from './priorNoticeDaysInCountType';
import { StartCountAdditionType } from './startCountAdditionType';
import { Syndicate } from './syndicate';
import { UseDifferentiatedNoticeType } from './useDifferentiatedNoticeType';


export interface PriorNotice { 
    daysAdditionInCount?: DaysAdditionInCountType;
    priorNoticeDaysInCount?: PriorNoticeDaysInCountType;
    /**
     * Acréscimo dias indenizado no ano
     */
    indemnifiedDaysAdditionYear?: number;
    syndicate: Syndicate;
    startCountAddition?: StartCountAdditionType;
    useDifferentiatedNotice?: UseDifferentiatedNoticeType;
    /**
     * Somar aviso reavido na rescisão
     */
    sumNoticeDaysRetrievedTermination?: boolean;
    /**
     * Data da última alteração do aviso prévio
     */
    dateWhen: string;
    formAdditionCount?: FormAdditionCountType;
    calculationAveragePriorNotice?: CalculationAveragePriorNoticeType;
    /**
     * Seleção por tempo de serviço
     */
    serviceTimeSelection?: boolean;
    /**
     * Dias aviso reavido
     */
    retrievedNoticeDays?: number;
    /**
     * Acréscimo dias reavido no ano
     */
    recoveredDaysAdditionYear?: number;
    /**
     * Seleção por idade
     */
    ageSelection?: boolean;
    /**
     * Id do aviso prévio
     */
    id?: string;
    formDisregardWithdrawalDay?: FormDisregardWithdrawalDayType;
    /**
     * Dias aviso indenizado
     */
    indemnifiedNoticeDays?: number;
}
