/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PriorNoticeDaysInCountType = 'FORECAST_COUNTING' | 'NOT_FORECAST';

export const PriorNoticeDaysInCountType = {
    FORECASTCOUNTING: 'FORECAST_COUNTING' as PriorNoticeDaysInCountType,
    NOTFORECAST: 'NOT_FORECAST' as PriorNoticeDaysInCountType
};
