/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type RacialType = 'NotInformed' | 'White' | 'Black' | 'Brown' | 'Yellow' | 'Indian';

export const RacialType = {
    NotInformed: 'NotInformed' as RacialType,
    White: 'White' as RacialType,
    Black: 'Black' as RacialType,
    Brown: 'Brown' as RacialType,
    Yellow: 'Yellow' as RacialType,
    Indian: 'Indian' as RacialType
};
