/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type RaisType = 'Type_10' | 'Type_15' | 'Type_20' | 'Type_25' | 'Type_30' | 'Type_31' | 'Type_35' | 'Type_40' | 'Type_49' | 'Type_50' | 'Type_55' | 'Type_60' | 'Type_65' | 'Type_70' | 'Type_75' | 'Type_80' | 'Type_90' | 'Type_95' | 'Type_96' | 'Type_97';

export const RaisType = {
  _10: 'Type_10' as RaisType,
  _15: 'Type_15' as RaisType,
  _20: 'Type_20' as RaisType,
  _25: 'Type_25' as RaisType,
  _30: 'Type_30' as RaisType,
  _31: 'Type_31' as RaisType,
  _35: 'Type_35' as RaisType,
  _40: 'Type_40' as RaisType,
  _49: 'Type_49' as RaisType,
  _50: 'Type_50' as RaisType,
  _55: 'Type_55' as RaisType,
  _60: 'Type_60' as RaisType,
  _65: 'Type_65' as RaisType,
  _70: 'Type_70' as RaisType,
  _75: 'Type_75' as RaisType,
  _80: 'Type_80' as RaisType,
  _90: 'Type_90' as RaisType,
  _95: 'Type_95' as RaisType,
  _96: 'Type_96' as RaisType,
  _97: 'Type_97' as RaisType
};
