/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Religion { 
    /**
     * Código da religião
     */
    code: number;
    /**
     * Descrição da religião
     */
    name: string;
    /**
     * Id da religião
     */
    id?: string;
}
