/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type SalaryType = 'Hourly' | 'Daily' | 'Weekly' | 'Fortnightly' | 'Monthly' | 'Takers' | 'Dynamic' | 'ThirdParty';

export const SalaryType = {
  Hourly: 'Hourly' as SalaryType,
  Daily: 'Daily' as SalaryType,
  Weekly: 'Weekly' as SalaryType,
  Fortnightly: 'Fortnightly' as SalaryType,
  Monthly: 'Monthly' as SalaryType,
  Takers: 'Takers' as SalaryType,
  Dynamic: 'Dynamic' as SalaryType,
  ThirdParty: 'ThirdParty' as SalaryType
};
