/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ScaleCategory { 
    /**
     * Código da categoria
     */
    code: number;
    /**
     * Descrição da categoria
     */
    name: string;
    /**
     * Id da categoria
     */
    id: string;
    /**
     * Cobre categoria
     */
    category: string;
    /**
     * Consistir cobre categoria?
     */
    consistCategory: boolean;
}
