/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type StartCountAdditionType = 'HIRE_DATE' | 'NEXT_YEAR_HIRE_DATE';

export const StartCountAdditionType = {
    HIREDATE: 'HIRE_DATE' as StartCountAdditionType,
    NEXTYEARHIREDATE: 'NEXT_YEAR_HIRE_DATE' as StartCountAdditionType
};
