/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SubgroupDisease { 
    /**
     * Código do Subgrupo de Doenças
     */
    code?: string;
    /**
     * Descrição do Subgrupo de Doenças
     */
    name?: string;
    /**
     * Identificador
     */
    id?: string;
}
