/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type SubscriptionType = 'EMPTY' | 'CNPJ' | 'CEI' | 'CPF' | 'INCRA';

export const SubscriptionType = {
  EMPTY: 'EMPTY' as SubscriptionType,
  CNPJ: 'CNPJ' as SubscriptionType,
  CEI: 'CEI' as SubscriptionType,
  CPF: 'CPF' as SubscriptionType,
  INCRA: 'INCRA' as SubscriptionType
};
