/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type TakersRoutineUseType = 'BY_COMPANY_BRANCH' | 'BY_APPORTIONMENT';

export const TakersRoutineUseType = {
    COMPANYBRANCH: 'BY_COMPANY_BRANCH' as TakersRoutineUseType,
    APPORTIONMENT: 'BY_APPORTIONMENT' as TakersRoutineUseType
};
