/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type UseDifferentiatedNoticeType = 'TYPE_1' | 'TYPE_2' | 'TYPE_3' | 'TYPE_4' | 'TYPE_5';

export const UseDifferentiatedNoticeType = {
  _1: 'TYPE_1' as UseDifferentiatedNoticeType,
  _2: 'TYPE_2' as UseDifferentiatedNoticeType,
  _3: 'TYPE_3' as UseDifferentiatedNoticeType,
  _4: 'TYPE_4' as UseDifferentiatedNoticeType,
  _5: 'TYPE_5' as UseDifferentiatedNoticeType
};
