/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type VacationRightType = 'TYPE_Q_1_12_EVERY_30_DAYS_AND_GREATER_THAN_15_DAYS_IN_THE_END' | 'TYPE_C_1_12_EVERY_CIVIL_MONTH_GREATER_15_DAYS' | 'TYPE_M_CONSIDER_THE_BIGGEST_OF_ALL';

export const VacationRightType = {
    Q112EVERY30DAYSANDGREATERTHAN15DAYSINTHEEND: 'TYPE_Q_1_12_EVERY_30_DAYS_AND_GREATER_THAN_15_DAYS_IN_THE_END' as VacationRightType,
    C112EVERYCIVILMONTHGREATER15DAYS: 'TYPE_C_1_12_EVERY_CIVIL_MONTH_GREATER_15_DAYS' as VacationRightType,
    MCONSIDERTHEBIGGESTOFALL: 'TYPE_M_CONSIDER_THE_BIGGEST_OF_ALL' as VacationRightType
};
