/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SalaryType } from './salaryType';


export interface Wagescale { 
    /**
     * Nome da estrutura salarial
     */
    name?: string;
    /**
     * ID da estrutura salarial
     */
    id?: string;
    salarytype?: SalaryType;
    /**
     * Sequência que corresponde ao salário de mercado
     */
    marketlevel?: number;
}
