/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type WorkshiftType = 'Permanent' | 'AutomaticSearch' | 'Defined' | 'AutomaticGeneration';

export const WorkshiftType = {
    Permanent: 'Permanent' as WorkshiftType,
    AutomaticSearch: 'AutomaticSearch' as WorkshiftType,
    Defined: 'Defined' as WorkshiftType,
    AutomaticGeneration: 'AutomaticGeneration' as WorkshiftType
};
