/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Costcenter } from './costcenter';
import { DecisionPcD } from './decisionPcD';
import { Department } from './department';
import { EmployeeContractType } from './employeeContractType';
import { EmploymentRelationship } from './employmentRelationship';
import { ExpenseNature } from './expenseNature';
import { IntervalGroup } from './intervalGroup';
import { ScaleCategory } from './scaleCategory';
import { ScaleTeam } from './scaleTeam';
import { Syndicate } from './syndicate';
import { Workshift } from './workshift';
import { WorkshiftGroup } from './workshiftGroup';
import { WorkshiftScale } from './workshiftScale';
import { Workstationgroupstructure } from './workstationgroupstructure';


export interface Workstationgroup { 
    employmentRelationship?: EmploymentRelationship;
    /**
     * Código do posto de trabalho
     */
    code?: string;
    workshiftGroup?: WorkshiftGroup;
    workshift?: Workshift;
    contractType: EmployeeContractType;
    allowDeficient: DecisionPcD;
    scaleCategory?: ScaleCategory;
    shift?: WorkshiftScale;
    syndicate?: Syndicate;
    /**
     * Data de criação do posto de trabalho
     */
    creationDate: string;
    /**
     * Relacionamento com o perfil de posto. (R017PER)
     */
    workstationGroupProfile?: string;
    intervalGroup?: IntervalGroup;
    headoffice: Company;
    workstationgroupstructure: Workstationgroupstructure;
    expenseNature?: ExpenseNature;
    branchoffice?: Company;
    scaleTeam?: ScaleTeam;
    /**
     * Nome do posto de trabalho
     */
    name: string;
    /**
     * Id do posto de trabalho
     */
    id?: string;
    department?: Department;
    costcenter?: Costcenter;
    /**
     * Data de expiração do posto de trabalho
     */
    expirationDate?: string;
}
