/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type WorkshiftScale = 'FIRST_SHIFT' | 'SECOND_SHIFT' | 'THIRD_SHIFT' | 'FOURTH_SHIFT' | 'MIXED' | 'GENERAL';

export const WorkshiftScale = {
    FIRSTSHIFT: 'FIRST_SHIFT' as WorkshiftScale,
    SECONDSHIFT: 'SECOND_SHIFT' as WorkshiftScale,
    THIRDSHIFT: 'THIRD_SHIFT' as WorkshiftScale,
    FOURTHSHIFT: 'FOURTH_SHIFT' as WorkshiftScale,
    MIXED: 'MIXED' as WorkshiftScale,
    GENERAL: 'GENERAL' as WorkshiftScale
};
