/**
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Employee } from './employee';
import { Workstationgroup } from './workstationgroup';


export interface Workstation { 
    company?: Company;
    /**
     * Id do posto de trabalho
     */
    id?: string;
    occupant?: Employee;
    workstationgroup?: Workstationgroup;
}
