/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Ability { 
    /**
     * Data de criação.
     */
    createdAt?: Date;
    /**
     * Identificador do currículo à qual a habilidade está associada.
     */
    resumeId?: string;
    /**
     * Descrição da habilidade.
     */
    description?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Data da última alteração.
     */
    updatedAt?: Date;
}
