/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type AprovationTypeDto = 'APPROVED' | 'REPROVED' | 'NOT_APPLICABLE';

export const AprovationTypeDto = {
    APPROVED: 'APPROVED' as AprovationTypeDto,
    REPROVED: 'REPROVED' as AprovationTypeDto,
    NOTAPPLICABLE: 'NOT_APPLICABLE' as AprovationTypeDto
};
