/**
 * recruitment
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Processo seletivo do candidato.
 */
export interface RecruitmentProcess { 
    /**
     * Candidato externo.
     */
    resume?: any;
    /**
     * Data e hora da criação da candidatura.
     */
    createdAt?: Date;
    /**
     * Identificador único do candidato externo.
     */
    resumeId?: string;
    /**
     * Identificador único do colaborador.
     */
    employeeId?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Justificativa para a reprovação/remoção do candidato no processo seletivo em questão (Se for o caso).
     */
    justification?: string;
    /**
     * Candidato interno
     */
    employee?: any;
    /**
     * Vaga.
     */
    vacancy?: any;
    /**
     * Identificador único da vaga.
     */
    vacancyId?: string;
    /**
     * Data e hora da última alteração na candidatura.
     */
    updatedAt?: Date;
    /**
     * Status do candidato na vaga.
     */
    status?: any;
}
