/**
 * recruitment
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Etapa do processo seletivo do candidato.
 */
export interface RecruitmentProcessStage { 
    /**
     * Processo a qual está etapa pertence.
     */
    process?: any;
    /**
     * Etapa do processo seletivo.
     */
    stage?: any;
    /**
     * Identificador único do processo a qual está etapa pertence.
     */
    processId?: string;
    /**
     * Status da ficha médica integrada.
     */
    seemMedicalStatus?: any;
    /**
     * Status para gerar a ficha médica e ASO.
     */
    integrationStatus?: any;
    /**
     * Data e hora de envio das informações para gerar a ficha médica e ASO.
     */
    integrationSendDate?: Date;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Identificador único do responsável por gerar a ficha médica e ASO.
     */
    integrationResponsiblePersonId?: string;
    /**
     * Data e hora de recepção da G5 do parecer da ficha médica e ASO.
     */
    integrationG5Date?: Date;
    /**
     * Responsável por gerar a ficha médica e ASO.
     */
    integrationResponsiblePerson?: any;
    /**
     * Status da etapa.
     */
    status?: any;
    /**
     * Identificador único da etapa do processo seletivo.
     */
    stageId?: string;
}
