/**
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RecruitmentProcessEmployee } from './recruitmentProcessEmployee';
import { RecruitmentProcessHistoryStatus } from './recruitmentProcessHistoryStatus';
import { RecruitmentProcessResume } from './recruitmentProcessResume';
import { RecruitmentProcessVacancy } from './recruitmentProcessVacancy';


/**
 * Processo seletivo do candidato.
 */
export interface RecruitmentProcess { 
    resume?: RecruitmentProcessResume;
    /**
     * Data e hora da criação da candidatura.
     */
    createdAt?: Date;
    /**
     * Identificador único do candidato externo.
     */
    resumeId?: string;
    /**
     * Identificador único do colaborador.
     */
    employeeId?: string;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * Justificativa para a reprovação/remoção do candidato no processo seletivo em questão (Se for o caso).
     */
    justification?: string;
    employee?: RecruitmentProcessEmployee;
    vacancy?: RecruitmentProcessVacancy;
    /**
     * Identificador único da vaga.
     */
    vacancyId?: string;
    /**
     * Data e hora da última alteração na candidatura.
     */
    updatedAt?: Date;
    status?: RecruitmentProcessHistoryStatus;
}
