/**
 * recruitment
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: develop-SNAPSHOT
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Vaga de emprego.
 */
export interface Vacancy { 
    /**
     * Motivo de abertura da vaga.
     */
    reason: any;
    /**
     * Comentário de conclusão
     */
    finalizationComment?: string;
    /**
     * Representa o posto de trabalho.
     */
    workstationGroup?: any;
    /**
     * Requisição da vaga.
     */
    requisition?: any;
    /**
     * Tipo de contrato de trabalho.
     */
    contractType?: any;
    /**
     * Data inicial da publicação da vaga para candidatos externos.
     */
    externalStartDate?: string;
    /**
     * Identificador do departamento
     */
    departmentId?: string;
    /**
     * Data de criação da vaga.
     */
    createdAt?: Date;
    /**
     * Situação da admissão do candidato escolhido para a vaga.
     */
    admissionSituation?: any;
    /**
     * Identificador único da entidade.
     */
    id?: string;
    /**
     * URL com o link do arquivo que contém o texto da publicação no BlobService.
     */
    locationURI?: string;
    /**
     * Solicitante da vaga.
     */
    requester?: any;
    /**
     * Turno de trabalho
     */
    workShift?: any;
    /**
     * Id do anexo de finalização da vaga
     */
    finalizationAttachmentId?: string;
    /**
     * Data prevista de admissão.
     */
    admissionDate?: string;
    /**
     * Identificador do posto de trabalho.
     */
    workstationGroupId?: string;
    /**
     * ID do solicitante da vaga.
     */
    requesterId?: string;
    /**
     * Centro de custo
     */
    costCenter?: any;
    /**
     * Quantidade de horas que a vaga ficou pendente com o solicitante.
     */
    pendencyHours?: number;
    /**
     * Versão do identificador do arquivo com o texto da publicação no BlobService.
     */
    version?: string;
    /**
     * Cargo da vaga.
     */
    jobPosition?: any;
    /**
     * Identificador da empresa
     */
    companyId?: string;
    /**
     * Fim da faixa salarial.
     */
    endSalaryRange?: string;
    /**
     * Identificador do cargo da vaga.
     */
    jobPositionId?: string;
    /**
     * Responsável por armazenar uma sequência única da RP na vaga.
     */
    sequenceStaffrequisitionVacancy?: any;
    /**
     * Colaborador que será substituido (Se for o caso).
     */
    replacedEmployee?: any;
    /**
     * Status da efetivação.
     */
    integrationStatus?: any;
    /**
     * Identificador do turno de trabalho
     */
    workShiftId?: string;
    /**
     * Identificador do arquivo com o texto da publicação no BlobService.
     */
    fileId?: string;
    /**
     * Identificador do questionário
     */
    questionnaire?: string;
    /**
     * Modelo de personalidade desejado para a vaga.
     */
    personalityModel?: any;
    /**
     * Tipo de vínculo empregatício da vaga.
     */
    employmentContract?: any;
    /**
     * ID do chat da vaga.
     */
    chatId?: string;
    /**
     * Indica se a vaga deve ser publicada para candidatos externos.
     */
    externalPublish?: boolean;
    /**
     * Descrição da vaga.
     */
    description: string;
    /**
     * Título da vaga.
     */
    title: string;
    /**
     * Id da requisição da vaga.
     */
    requisitionId?: string;
    /**
     * Indica se a vaga deve estar em destaque.
     */
    highlight?: boolean;
    /**
     * Data final da publicação da vaga para candidatos internos.
     */
    internalEndDate?: string;
    /**
     * Identificador do centro de custo
     */
    costCenterId?: string;
    /**
     * Indica se a vaga possui alguma pendência registrada.
     */
    hasPendencyRegistered?: boolean;
    /**
     * Indica se a vaga deve ser publicada para candidatos internos.
     */
    internalPublish?: boolean;
    /**
     * Analista de RH responsável pela vaga.
     */
    responsible?: any;
    /**
     * Empresa
     */
    company?: any;
    /**
     * Justificativa para a abertura da vaga.
     */
    justification: string;
    /**
     * Departamento
     */
    department?: any;
    /**
     * Situação atual da vaga.
     */
    situation?: any;
    /**
     * Início da faixa salarial.
     */
    startSalaryRange?: string;
    /**
     * Data inicial da publicação da vaga para candidatos internos.
     */
    internalStartDate?: string;
    /**
     * Data final da publicação da vaga para candidatos externos.
     */
    externalEndDate?: string;
    /**
     * ID do colaborador que será substituido (Se for o caso).
     */
    replacedEmployeeId?: string;
    /**
     * Indica que a vaga está pendente com o solicitante.
     */
    pendingWithRequester?: boolean;
    /**
     * Indica se a vaga já possui candidatos.
     */
    hasCandidates?: boolean;
    /**
     * Identificador do responsável por armazenar uma sequência única da RP na vaga.
     */
    sequenceStaffrequisitionVacancyId?: string;
    /**
     * Data e hora de conclusão da vaga
     */
    finalizedAt?: Date;
    /**
     * Chat da vaga.
     */
    chat?: any;
    /**
     * Progresso da vaga.
     */
    progress?: number;
    /**
     * Local da vaga.
     */
    location?: string;
}
