/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type AccessCallOrigin = 'DEVICE_INPUT' | 'DEVICE_READER' | 'SELFSERVICE_TERMINAL';

export const AccessCallOrigin = {
    DEVICEINPUT: 'DEVICE_INPUT' as AccessCallOrigin,
    DEVICEREADER: 'DEVICE_READER' as AccessCallOrigin,
    SELFSERVICETERMINAL: 'SELFSERVICE_TERMINAL' as AccessCallOrigin
};
