/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessCreditRange } from './accessCreditRange';
import { HolidayList } from './holidayList';


export interface AccessCreditRangeList { 
    /**
     * Nome da Lista
     */
    name?: string;
    /**
     * ID
     */
    id?: number;
    holidayList?: HolidayList;
    /**
     * Lista de Faixas de Crédito de Acesso
     */
    accessCreditRanges?: Array<AccessCreditRange>;
}
