/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessCallOrigin } from './accessCallOrigin';
import { AccessCallStatus } from './accessCallStatus';
import { InputDeviceAccessCall } from './inputDeviceAccessCall';
import { ReaderDeviceAccessCall } from './readerDeviceAccessCall';
import { VirtualLobby } from './virtualLobby';
import { VirtualLobbyMovement } from './virtualLobbyMovement';
import { VirtualLobbyMovementType } from './virtualLobbyMovementType';
import { VisitAccessCall } from './visitAccessCall';


export interface AccessCall { 
    visitAccessCall?: VisitAccessCall;
    accessCallOrigin?: AccessCallOrigin;
    /**
     * Data Fim
     */
    endDate?: Date;
    inputDeviceAccessCall?: InputDeviceAccessCall;
    /**
     * Data da Criação
     */
    creationDate?: Date;
    accessCallStatus?: AccessCallStatus;
    /**
     * Nome usuário
     */
    userName?: string;
    virtualLobby?: VirtualLobby;
    virtualLobbyMovementType?: VirtualLobbyMovementType;
    /**
     * ID
     */
    id?: number;
    readerDeviceAccessCall?: ReaderDeviceAccessCall;
    /**
     * Data Início
     */
    startDate?: Date;
    virtualLobbyMovement?: VirtualLobbyMovement;
}
