/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type BiometricOneToOneValidationType = 'NONE' | 'OPTIONAL' | 'REQUIRED';

export const BiometricOneToOneValidationType = {
    NONE: 'NONE' as BiometricOneToOneValidationType,
    OPTIONAL: 'OPTIONAL' as BiometricOneToOneValidationType,
    REQUIRED: 'REQUIRED' as BiometricOneToOneValidationType
};
