/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type BiometricManufacturer = 'NONE' | 'FINGERPRINT_SAGEM' | 'FINGERPRINT_SUPREMA' | 'FINGERPRINT_VIRDI' | 'FINGERPRINT_NITGEN' | 'FINGERPRINT_CAMA' | 'FINGERPRINT_INNOVATRICS' | 'HANDKEY_IR' | 'FACIAL';

export const BiometricManufacturer = {
    NONE: 'NONE' as BiometricManufacturer,
    FINGERPRINTSAGEM: 'FINGERPRINT_SAGEM' as BiometricManufacturer,
    FINGERPRINTSUPREMA: 'FINGERPRINT_SUPREMA' as BiometricManufacturer,
    FINGERPRINTVIRDI: 'FINGERPRINT_VIRDI' as BiometricManufacturer,
    FINGERPRINTNITGEN: 'FINGERPRINT_NITGEN' as BiometricManufacturer,
    FINGERPRINTCAMA: 'FINGERPRINT_CAMA' as BiometricManufacturer,
    FINGERPRINTINNOVATRICS: 'FINGERPRINT_INNOVATRICS' as BiometricManufacturer,
    HANDKEYIR: 'HANDKEY_IR' as BiometricManufacturer,
    FACIAL: 'FACIAL' as BiometricManufacturer
};
