/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BlueprintCamera } from './blueprintCamera';
import { BlueprintDevice } from './blueprintDevice';
import { BlueprintPhysicalLocation } from './blueprintPhysicalLocation';
import { PhysicalLocation } from './physicalLocation';


export interface Blueprint { 
    /**
     * Lista de Câmeras
     */
    cameras?: Array<BlueprintCamera>;
    /**
     * Local físico
     */
    physicalLocation?: Array<PhysicalLocation>;
    /**
     * Cores Invertidas
     */
    invertedColors?: boolean;
    /**
     * Lista de Dispositivos
     */
    devices?: Array<BlueprintDevice>;
    /**
     * Lista de Locais Físicos
     */
    physicalLocationsChildren?: Array<BlueprintPhysicalLocation>;
    /**
     * ID
     */
    id?: number;
}
