/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CallGenerationType = 'DISABLED' | 'ALWAYS' | 'ON_ACCESS_ALLOWED' | 'ON_ACCESS_DENIED';

export const CallGenerationType = {
    DISABLED: 'DISABLED' as CallGenerationType,
    ALWAYS: 'ALWAYS' as CallGenerationType,
    ONACCESSALLOWED: 'ON_ACCESS_ALLOWED' as CallGenerationType,
    ONACCESSDENIED: 'ON_ACCESS_DENIED' as CallGenerationType
};
