/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CameraDevice } from './cameraDevice';
import { CameraStatus } from './cameraStatus';
import { CctvProxy } from './cctvProxy';
import { DvrServer } from './dvrServer';
import { PhysicalLocation } from './physicalLocation';


export interface Camera { 
    dvrServer?: DvrServer;
    /**
     * Câmera PTZ
     */
    isPTZ?: boolean;
    physicalLocation?: PhysicalLocation;
    /**
     * Relação Câmera e Dispositivos
     */
    devices?: Array<CameraDevice>;
    /**
     * Url de streaming
     */
    urlStreaming?: string;
    /**
     * Nome
     */
    name?: string;
    cctvProxy?: CctvProxy;
    /**
     * ID
     */
    id?: number;
    /**
     * Servidor da Câmera
     */
    cameraServerId?: string;
    /**
     * Link do Stream da Câmera
     */
    streamLink?: string;
    status?: CameraStatus;
}
