/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CardTechnology = 'NONE' | 'BARCODE_CARD' | 'RFID_CARD' | 'SMART_CARD';

export const CardTechnology = {
    NONE: 'NONE' as CardTechnology,
    BARCODECARD: 'BARCODE_CARD' as CardTechnology,
    RFIDCARD: 'RFID_CARD' as CardTechnology,
    SMARTCARD: 'SMART_CARD' as CardTechnology
};
