/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type CredentialFormat = 'CARD' | 'BIOMETRY' | 'LICENSE_PLATE' | 'QRCODE' | 'BLUETOOTH';

export const CredentialFormat = {
    CARD: 'CARD' as CredentialFormat,
    BIOMETRY: 'BIOMETRY' as CredentialFormat,
    LICENSEPLATE: 'LICENSE_PLATE' as CredentialFormat,
    QRCODE: 'QRCODE' as CredentialFormat,
    BLUETOOTH: 'BLUETOOTH' as CredentialFormat
};
