/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeviceCommunicationStatus } from './deviceCommunicationStatus';
import { DeviceSituation } from './deviceSituation';
import { DeviceType } from './deviceType';
import { ExtensibleConfiguration } from './extensibleConfiguration';
import { PhysicalLocation } from './physicalLocation';


export interface Device { 
    deviceType?: DeviceType;
    parent?: Device;
    physicalLocation?: PhysicalLocation;
    communicationStatus?: DeviceCommunicationStatus;
    extensibleConfiguration?: ExtensibleConfiguration;
    /**
     * Descrição do Dispositivo
     */
    description?: string;
    /**
     * ID
     */
    id?: number;
    /**
     * Dispositivo gerenciador
     */
    managerDeviceId?: number;
    situation?: DeviceSituation;
    /**
     * Dispositivo Integrado
     */
    integrated?: boolean;
}
