/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DeviceType = 'MANAGER' | 'READER' | 'MODULE' | 'INPUT' | 'OUTPUT';

export const DeviceType = {
    MANAGER: 'MANAGER' as DeviceType,
    READER: 'READER' as DeviceType,
    MODULE: 'MODULE' as DeviceType,
    INPUT: 'INPUT' as DeviceType,
    OUTPUT: 'OUTPUT' as DeviceType
};
