/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DvrServerType } from './dvrServerType';


export interface DvrServer { 
    /**
     * Senha de Acesso
     */
    password?: string;
    /**
     * Porta de Comunicação
     */
    port?: number;
    /**
     * Prefixo da URL
     */
    urlPrefix?: string;
    /**
     * Nome do Servidor
     */
    name?: string;
    dvrServerType?: DvrServerType;
    /**
     * Identificador de Rede
     */
    host?: string;
    /**
     * ID
     */
    id?: number;
    /**
     * Usuário de Acesso
     */
    user?: string;
    /**
     * Identificador do Servidor
     */
    serverId?: string;
    /**
     * Domínio de Rede
     */
    networkDomain?: string;
}
