/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupPerson } from './groupPerson';
import { PhysicalLocation } from './physicalLocation';


export interface Group { 
    parent?: Group;
    physicalLocation?: PhysicalLocation;
    /**
     * Vaga de Estacionamento em Uso
     */
    parkingSpaceInUse?: number;
    /**
     * Caminho hierárquico completo
     */
    fullHierarchicalPath?: string;
    /**
     * Nome do Grupo
     */
    name?: string;
    /**
     * ID
     */
    id?: number;
    /**
     * Pessoas do Grupo
     */
    people?: Array<GroupPerson>;
    /**
     * Vaga de Estacionamento
     */
    parkingSpace?: number;
}
