/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type IncidentPriority = 'PLANNED' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export const IncidentPriority = {
    PLANNED: 'PLANNED' as IncidentPriority,
    LOW: 'LOW' as IncidentPriority,
    MEDIUM: 'MEDIUM' as IncidentPriority,
    HIGH: 'HIGH' as IncidentPriority,
    CRITICAL: 'CRITICAL' as IncidentPriority
};
