/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InputDevice } from './inputDevice';


export interface InputMasking { 
    /**
     * Hora Final
     */
    endHour?: string;
    /**
     * Domingo
     */
    sunday?: boolean;
    /**
     * Sábado
     */
    saturday?: boolean;
    /**
     * Hora Inicial
     */
    startHour?: string;
    inputDevice?: InputDevice;
    /**
     * Dias da Semana
     */
    businessDays?: boolean;
    /**
     * ID
     */
    id?: number;
    /**
     * Feriado
     */
    holiday?: boolean;
}
