/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Device } from './device';
import { DeviceCommunicationStatus } from './deviceCommunicationStatus';
import { DeviceSituation } from './deviceSituation';
import { DeviceType } from './deviceType';
import { ExtensibleConfiguration } from './extensibleConfiguration';
import { IncidentPriority } from './incidentPriority';
import { IncidentType } from './incidentType';
import { InputMasking } from './inputMasking';
import { InputState } from './inputState';
import { OutputDeviceActivations } from './outputDeviceActivations';
import { PhysicalLocation } from './physicalLocation';


export interface InputDevice { 
    deviceType?: DeviceType;
    parent?: Device;
    /**
     * Endereço
     */
    address?: number;
    physicalLocation?: PhysicalLocation;
    defaultState?: InputState;
    incidentPriority?: IncidentPriority;
    incidentType?: IncidentType;
    /**
     * Descrição do Dispositivo
     */
    description?: string;
    /**
     * Mascaramentos da Entrada
     */
    masks?: Array<InputMasking>;
    /**
     * Dispositivo Integrado
     */
    integrated?: boolean;
    communicationStatus?: DeviceCommunicationStatus;
    /**
     * Gera Incidente
     */
    generateIncident?: boolean;
    extensibleConfiguration?: ExtensibleConfiguration;
    /**
     * Acionamentos
     */
    activations?: Array<OutputDeviceActivations>;
    inputState?: InputState;
    /**
     * ID
     */
    id?: number;
    /**
     * Delay de Ativação da Entrada
     */
    activationDelay?: number;
    situation?: DeviceSituation;
}
