/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OffsetDaylightSavingType } from './offsetDaylightSavingType';
import { Timezone } from './timezone';


export interface LocalTimezone { 
    /**
     * Data início do horário de verão
     */
    daylightSavingStartDate?: string;
    /**
     * Horário de verão
     */
    daylightSaving?: boolean;
    timezone?: Timezone;
    /**
     * Nome do Local
     */
    name?: string;
    offsetDaylightSaving?: OffsetDaylightSavingType;
    /**
     * ID
     */
    id?: number;
    /**
     * Data fim do horário de verão
     */
    daylightSavingFinishDate?: string;
}
