/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OffsetDaylightSavingType = 'NONE_OFFSET' | 'MINUS_ONE_HOUR' | 'PLUS_ONE_HOUR';

export const OffsetDaylightSavingType = {
    NONEOFFSET: 'NONE_OFFSET' as OffsetDaylightSavingType,
    MINUSONEHOUR: 'MINUS_ONE_HOUR' as OffsetDaylightSavingType,
    PLUSONEHOUR: 'PLUS_ONE_HOUR' as OffsetDaylightSavingType
};
