/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrganizationalStructurePerson } from './organizationalStructurePerson';
import { OrganizationalStructureType } from './organizationalStructureType';


export interface OrganizationalStructure { 
    /**
     * Estrutura organizacional pai
     */
    parent?: number;
    /**
     * Pessoas da estrutura organizacional
     */
    organizationalStructurePeople?: Array<OrganizationalStructurePerson>;
    /**
     * Descrição
     */
    description?: string;
    /**
     * ID
     */
    id?: number;
    organizationalStructureType?: OrganizationalStructureType;
    /**
     * Realiza Validação de Papel
     */
    integrated?: boolean;
}
