/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Biometry } from './biometry';
import { Credential } from './credential';
import { Document } from './document';
import { Email } from './email';
import { Gender } from './gender';
import { GroupPerson } from './groupPerson';
import { OrganizationalStructurePerson } from './organizationalStructurePerson';
import { PersonRole } from './personRole';
import { PersonSituation } from './personSituation';
import { PersonSituationType } from './personSituationType';
import { PersonVehicle } from './personVehicle';
import { PersonWorkSchedulePeriod } from './personWorkSchedulePeriod';
import { Phone } from './phone';
import { PhysicalLocation } from './physicalLocation';
import { User } from './user';


export interface Person { 
    /**
     * Data de Nascimento
     */
    birthday?: string;
    /**
     * Papéis da Pessoa
     */
    personRoles?: Array<PersonRole>;
    /**
     * Faixas horárias da pessoa
     */
    workSchedulePeriods?: Array<PersonWorkSchedulePeriod>;
    /**
     * Código Postal
     */
    zipCode?: string;
    gender?: Gender;
    /**
     * Cidade
     */
    city?: string;
    /**
     * Documento
     */
    documents?: Array<Document>;
    /**
     * Credênciais da pessoa
     */
    credentials?: Array<Credential>;
    /**
     * Telefone
     */
    phones?: Array<Phone>;
    /**
     * Email
     */
    emails?: Array<Email>;
    /**
     * Data da Última Alteração
     */
    lastModificationDate?: Date;
    physicalLocationWhereLevelUpdated?: PhysicalLocation;
    /**
     * ID
     */
    id?: number;
    situation?: PersonSituationType;
    /**
     * Data de Cadastro
     */
    registerDate?: Date;
    /**
     * Lista de Situação da Pessoa
     */
    situations?: Array<PersonSituation>;
    /**
     * Veículos da Pessoa
     */
    personVehicle?: Array<PersonVehicle>;
    /**
     * Matricula
     */
    registry?: string;
    /**
     * Endereço
     */
    address?: string;
    /**
     * Data do Último Acesso Permitido
     */
    lastAccessAllowedDate?: Date;
    lastAccessAllowedPhysicalLocation?: PhysicalLocation;
    /**
     * Grupos
     */
    groups?: Array<GroupPerson>;
    currentPhysicalLocation?: PhysicalLocation;
    /**
     * Data da Atualização da Foto
     */
    photoDate?: Date;
    /**
     * Biometrias da Pessoa
     */
    biometries?: Array<Biometry>;
    /**
     * Nacionalidade
     */
    nationality?: string;
    /**
     * Último Acesso
     */
    lastAccessDate?: Date;
    /**
     * Bairro
     */
    district?: string;
    /**
     * Nome
     */
    name?: string;
    /**
     * Estado
     */
    federalState?: string;
    /**
     * Usuário
     */
    user?: Array<User>;
    /**
     * Estruturas organizacionais da pessoa
     */
    organizationalStructuresPerson?: Array<OrganizationalStructurePerson>;
}
