/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Person } from './person';
import { PhoneType } from './phoneType';


export interface Phone { 
    /**
     * Telefone Preferencial
     */
    preferential?: boolean;
    /**
     * Número do Telefone
     */
    number?: string;
    phoneType?: PhoneType;
    person?: Person;
    /**
     * Ramal
     */
    phoneExtension?: string;
    /**
     * DDI/IDD (International Direct Dialing)
     */
    idd?: number;
    /**
     * ID
     */
    id?: number;
}
