/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Blueprint } from './blueprint';
import { LocalTimezone } from './localTimezone';
import { PhysicalLocationStatus } from './physicalLocationStatus';
import { RoleAccessPhysicalLocation } from './roleAccessPhysicalLocation';
import { TimeSlotList } from './timeSlotList';


export interface PhysicalLocation { 
    /**
     * Papel Acessa Local Físico
     */
    roleAccessPhysicalLocations?: Array<RoleAccessPhysicalLocation>;
    /**
     * Local Físico Pai
     */
    parent?: number;
    /**
     * Realiza Validação da Antidupla
     */
    antiPassbackValidation?: boolean;
    /**
     * Realiza validação de interjonada
     */
    checkInBetweenWorkdays?: boolean;
    /**
     * Realiza Validação da Faixa Horária do Papel
     */
    slotTimeRoleValidation?: boolean;
    /**
     * Tempo da Antidupla
     */
    antiPassbackTimeout?: number;
    timeSlotList?: TimeSlotList;
    localTimezone?: LocalTimezone;
    /**
     * Local Físico Externo
     */
    externalPhysicalLocation?: boolean;
    blueprint?: Blueprint;
    /**
     * Url da Validação Customizada
     */
    customValidationUrl?: string;
    /**
     * Realiza Validação da Suspensão do Papel
     */
    roleSuspensionValidation?: boolean;
    /**
     * Realiza Validação da Faixa Horária do Local Físico
     */
    slotTimePhysicalValidation?: boolean;
    /**
     * Realiza Validação do Autorizador do Local Físico
     */
    physicalLocationAuthorizerValidation?: boolean;
    /**
     * Realiza Validação do Autorizador do Papel
     */
    roleAuthorizerValidation?: boolean;
    /**
     * Realiza Validação de Crédito de Acesso
     */
    accessCreditValidation?: boolean;
    /**
     * Realiza Validação de Papel
     */
    roleValidation?: boolean;
    /**
     * Nome
     */
    name?: string;
    /**
     * Realiza Validação Customizada
     */
    customValidation?: boolean;
    /**
     * ID
     */
    id?: number;
    /**
     * Realiza Validação do Nível
     */
    levelValidation?: boolean;
    /**
     * Realiza Validação de Lotação
     */
    capacityValidation?: boolean;
    status?: PhysicalLocationStatus;
}
