/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ReaderDeviceTechnology = 'BARCODE_CARD' | 'RFID_CARD' | 'SMART_CARD' | 'BIOMETRIC' | 'QRCODE' | 'BLUETOOTH' | 'KEYBOARD';

export const ReaderDeviceTechnology = {
    BARCODECARD: 'BARCODE_CARD' as ReaderDeviceTechnology,
    RFIDCARD: 'RFID_CARD' as ReaderDeviceTechnology,
    SMARTCARD: 'SMART_CARD' as ReaderDeviceTechnology,
    BIOMETRIC: 'BIOMETRIC' as ReaderDeviceTechnology,
    QRCODE: 'QRCODE' as ReaderDeviceTechnology,
    BLUETOOTH: 'BLUETOOTH' as ReaderDeviceTechnology,
    KEYBOARD: 'KEYBOARD' as ReaderDeviceTechnology
};
