/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ValidationSetup = 'DISABLED' | 'ENABLED' | 'NOT_CONFIGURED';

export const ValidationSetup = {
    DISABLED: 'DISABLED' as ValidationSetup,
    ENABLED: 'ENABLED' as ValidationSetup,
    NOTCONFIGURED: 'NOT_CONFIGURED' as ValidationSetup
};
