/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type VehicleColor = 'UNDEFINED' | 'BLACK' | 'WHITE' | 'SILVER' | 'RED' | 'GREY' | 'BLUE' | 'YELLOW' | 'GREEN' | 'ORANGE' | 'OTHERS';

export const VehicleColor = {
    UNDEFINED: 'UNDEFINED' as VehicleColor,
    BLACK: 'BLACK' as VehicleColor,
    WHITE: 'WHITE' as VehicleColor,
    SILVER: 'SILVER' as VehicleColor,
    RED: 'RED' as VehicleColor,
    GREY: 'GREY' as VehicleColor,
    BLUE: 'BLUE' as VehicleColor,
    YELLOW: 'YELLOW' as VehicleColor,
    GREEN: 'GREEN' as VehicleColor,
    ORANGE: 'ORANGE' as VehicleColor,
    OTHERS: 'OTHERS' as VehicleColor
};
