/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessCall } from './accessCall';
import { MovementDirection } from './movementDirection';
import { Person } from './person';
import { Role } from './role';
import { VirtualLobby } from './virtualLobby';


export interface VirtualLobbyMovement { 
    virtualLobby?: VirtualLobby;
    /**
     * Data de criação
     */
    createdAt?: Date;
    role?: Role;
    movementDirection?: MovementDirection;
    accessCall?: AccessCall;
    responsible?: Person;
    visited?: Person;
    /**
     * ID
     */
    id?: number;
    visitor?: Person;
}
