/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Group } from './group';
import { PhysicalLocation } from './physicalLocation';
import { VirtualLobbyAction } from './virtualLobbyAction';
import { VirtualLobbyCamera } from './virtualLobbyCamera';
import { VirtualLobbyDevice } from './virtualLobbyDevice';
import { VirtualLobbySituation } from './virtualLobbySituation';


export interface VirtualLobby { 
    /**
     * Câmeras da Portaria Virtual
     */
    cameras?: Array<VirtualLobbyCamera>;
    destinationPhysicalLocation?: PhysicalLocation;
    physicalLocation?: PhysicalLocation;
    /**
     * Dispositivos da Portaria Virtual
     */
    devices?: Array<VirtualLobbyDevice>;
    /**
     * Nome
     */
    name?: string;
    /**
     * Descrição
     */
    description?: string;
    /**
     * ID
     */
    id?: number;
    originPhysicalLocation?: PhysicalLocation;
    /**
     * Acionamentos da Portaria Virtual
     */
    actions?: Array<VirtualLobbyAction>;
    situation?: VirtualLobbySituation;
    group?: Group;
}
