/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Device } from './device';
import { VirtualLobbyAction } from './virtualLobbyAction';
import { VirtualLobbyActionType } from './virtualLobbyActionType';


export interface VirtualLobbyActionOutput { 
    /**
     * Tempo do Acionamento
     */
    actionTime?: number;
    virtualLobbyActionType?: VirtualLobbyActionType;
    outputDevice?: Device;
    virtualLobbyAction?: VirtualLobbyAction;
    /**
     * ID
     */
    id?: number;
}
