/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type VirtualLobbyMovementType = 'ISSUE_ACCESS_CREDENTIAL' | 'REGISTER_LEAVE' | 'REGISTER_ENTRY';

export const VirtualLobbyMovementType = {
    ISSUEACCESSCREDENTIAL: 'ISSUE_ACCESS_CREDENTIAL' as VirtualLobbyMovementType,
    REGISTERLEAVE: 'REGISTER_LEAVE' as VirtualLobbyMovementType,
    REGISTERENTRY: 'REGISTER_ENTRY' as VirtualLobbyMovementType
};
