/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VirtualLobby } from './virtualLobby';
import { VirtualLobbyActionOutput } from './virtualLobbyActionOutput';
import { VirtualLobbyMovementType } from './virtualLobbyMovementType';


export interface VirtualLobbyAction { 
    /**
     * Saídas do Acionamento
     */
    outputs?: Array<VirtualLobbyActionOutput>;
    virtualLobby?: VirtualLobby;
    virtualLobbyMovementType?: VirtualLobbyMovementType;
    /**
     * Nome
     */
    name?: string;
    /**
     * ID
     */
    id?: number;
    /**
     * Acionamento Ativo
     */
    isActive?: boolean;
}
