/**
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type WeekDay = 'SUNDAY' | 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY';

export const WeekDay = {
    SUNDAY: 'SUNDAY' as WeekDay,
    MONDAY: 'MONDAY' as WeekDay,
    TUESDAY: 'TUESDAY' as WeekDay,
    WEDNESDAY: 'WEDNESDAY' as WeekDay,
    THURSDAY: 'THURSDAY' as WeekDay,
    FRIDAY: 'FRIDAY' as WeekDay,
    SATURDAY: 'SATURDAY' as WeekDay
};
