/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type AccountType = 'CURRENT_ACCOUNT' | 'SAVING_ACCOUNT' | 'SALARY_ACCOUNT' | 'OTHER';

export const AccountType = {
  CURRENTACCOUNT: 'CURRENT_ACCOUNT' as AccountType,
  SAVINGACCOUNT: 'SAVING_ACCOUNT' as AccountType,
  SALARYACCOUNT: 'SALARY_ACCOUNT' as AccountType,
  OTHER: 'OTHER' as AccountType
};
