/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from './addressType';
import { City } from './city';
import { Neighborhood } from './neighborhood';


export interface Address { 
    neighborhoodId?: Neighborhood;
    /**
     * Número do endereço.
     */
    number?: string;
    /**
     * Endereço.
     */
    address?: string;
    /**
     * Código postal do endereço (CEP)
     */
    postalcode?: string;
    /**
     * Informação adicional referente ao endereço.
     */
    additional?: string;
    addresstype?: AddressType;
    /**
     * Id da entidade
     */
    id?: string;
    cityId?: City;
}
