/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ApiType = 'PRIVATE' | 'PUBLIC';

export const ApiType = {
    PRIVATE: 'PRIVATE' as ApiType,
    PUBLIC: 'PUBLIC' as ApiType
};
