/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountType } from './accountType';
import { Bank } from './bank';
import { BankBranch } from './bankBranch';


export interface BankAccount { 
    /**
     * Conta bancária.
     */
    bankAccount: string;
    bank: Bank;
    bankBranch: BankBranch;
    accountType: AccountType;
    /**
     * Id da entidade
     */
    id?: string;
    /**
     * Digito da conta
     */
    digit?: string;
}
