/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DecisionType = 'YES' | 'NO';

export const DecisionType = {
    YES: 'YES' as DecisionType,
    NO: 'NO' as DecisionType
};
