/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type DegreeInstructionType = 'Illiterate' | 'ElementarySchoolIncomplete' | 'ElementarySchoolComplete' | 'MiddleSchoolIncomplete' | 'MiddleSchoolComplete' | 'HighSchoolIncomplete' | 'HighSchoolComplete' | 'BachelorIncomplete' | 'BachelorComplete' | 'Postgraduate' | 'Master' | 'Doctoral';

export const DegreeInstructionType = {
  Illiterate: 'Illiterate' as DegreeInstructionType,
  ElementarySchoolIncomplete: 'ElementarySchoolIncomplete' as DegreeInstructionType,
  ElementarySchoolComplete: 'ElementarySchoolComplete' as DegreeInstructionType,
  MiddleSchoolIncomplete: 'MiddleSchoolIncomplete' as DegreeInstructionType,
  MiddleSchoolComplete: 'MiddleSchoolComplete' as DegreeInstructionType,
  HighSchoolIncomplete: 'HighSchoolIncomplete' as DegreeInstructionType,
  HighSchoolComplete: 'HighSchoolComplete' as DegreeInstructionType,
  BachelorIncomplete: 'BachelorIncomplete' as DegreeInstructionType,
  BachelorComplete: 'BachelorComplete' as DegreeInstructionType,
  Postgraduate: 'Postgraduate' as DegreeInstructionType,
  Master: 'Master' as DegreeInstructionType,
  Doctoral: 'Doctoral' as DegreeInstructionType
};
