/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dependent } from './dependent';


export interface DependentIncomeTax { 
    /**
     * Inicio da competência
     */
    beginCompetence?: string;
    /**
     * Fim da competência
     */
    endCompetence?: string;
    /**
     * Idade limite imposto de renda
     */
    ageLimitIncomeTax?: number;
    /**
     * Id da entidade
     */
    id?: string;
    dependent?: Dependent;
}
