/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DegreeInstructionType } from './degreeInstructionType';


export interface Educationdegree { 
    /**
     * Código do grau de instrução
     */
    code?: number;
    nameRais?: DegreeInstructionType;
    /**
     * Nome do grau de instrução
     */
    name?: string;
    /**
     * Id do grau de instrução
     */
    id?: string;
}
