/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { EmployeeType } from './employeeType';
import { Person } from './person';


export interface Employee { 
    employeetype?: EmployeeType;
    person?: Person;
    /**
     * Empresa do colaborador: NUMEMP
     */
    companynumber?: number;
    employer?: Company;
    /**
     * Id do colaborador
     */
    id?: string;
    /**
     * Data de admissão
     */
    hiredate?: string;
    /**
     * Código do colaborador: NUMCAD
     */
    registernumber?: number;
}
