/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EmployeeType = 'NULLO' | 'EMPLOYEE' | 'THIRD' | 'PARTNER';

export const EmployeeType = {
    NULLO: 'NULLO' as EmployeeType,
    EMPLOYEE: 'EMPLOYEE' as EmployeeType,
    THIRD: 'THIRD' as EmployeeType,
    PARTNER: 'PARTNER' as EmployeeType
};
