/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ESocialDependentType = 'DontTakeDependent' | 'Spouse' | 'Partner' | 'SonStepson' | 'SonStepsonStudent' | 'SiblingGrandsonGreat' | 'SiblingGrandsonGreatStudent' | 'ParentsGrandparentsGreat' | 'PoorMinor' | 'IncapablePerson' | 'ExSpouse' | 'AggregateOthers';

export const ESocialDependentType = {
  DontTakeDependent: 'DontTakeDependent' as ESocialDependentType,
  Spouse: 'Spouse' as ESocialDependentType,
  Partner: 'Partner' as ESocialDependentType,
  SonStepson: 'SonStepson' as ESocialDependentType,
  SonStepsonStudent: 'SonStepsonStudent' as ESocialDependentType,
  SiblingGrandsonGreat: 'SiblingGrandsonGreat' as ESocialDependentType,
  SiblingGrandsonGreatStudent: 'SiblingGrandsonGreatStudent' as ESocialDependentType,
  ParentsGrandparentsGreat: 'ParentsGrandparentsGreat' as ESocialDependentType,
  PoorMinor: 'PoorMinor' as ESocialDependentType,
  IncapablePerson: 'IncapablePerson' as ESocialDependentType,
  ExSpouse: 'ExSpouse' as ESocialDependentType,
  AggregateOthers: 'AggregateOthers' as ESocialDependentType
};
