/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type FgtsPensionType = 'NOT_APPLICABLE' | 'VALUE' | 'PERCENTAGE';

export const FgtsPensionType = {
    NOTAPPLICABLE: 'NOT_APPLICABLE' as FgtsPensionType,
    VALUE: 'VALUE' as FgtsPensionType,
    PERCENTAGE: 'PERCENTAGE' as FgtsPensionType
};
