/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FgtsPensionType = 'NOT_APPLICABLE' | 'VALUE' | 'PERCENTAGE';

export const FgtsPensionType = {
  NOT_APPLICABLE: 'NOT_APPLICABLE' as FgtsPensionType,
  VALUE: 'VALUE' as FgtsPensionType,
  PERCENTAGE: 'PERCENTAGE' as FgtsPensionType
};
