/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DecisionType } from './decisionType';
import { FinancialIndex } from './financialIndex';
import { Salary13Type } from './salary13Type';
import { SalaryAdvancedType } from './salaryAdvancedType';


export interface FixedJudicialValue { 
    financialIndex?: FinancialIndex;
    vacationType?: DecisionType;
    /**
     * Porcentagem do adiantamento salarial para a pensão
     */
    salaryAdvancedPercentage?: number;
    /**
     * Data de inicio da correção
     */
    startCorrection?: string;
    /**
     * Periodicidade da correção
     */
    periodicityCorrection?: number;
    /**
     * Id da entidade
     */
    id?: string;
    salary13Type?: Salary13Type;
    salaryAdvancedType?: SalaryAdvancedType;
    wageBonusType?: DecisionType;
    /**
     * Valor inicial
     */
    initialValue?: number;
    /**
     * Dia da correção
     */
    correctionDay?: number;
}
