/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type GenderType = 'Male' | 'Female';

export const GenderType = {
    Male: 'Male' as GenderType,
    Female: 'Female' as GenderType
};
