/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type IndexType = 'OTHER' | 'UFIR' | 'URV' | 'ITRD' | 'SELIC' | 'CONTRIBUTION_SALARY_CORRECTION' | 'SAVINGS_CORRECTION' | 'CURRENCY';

export const IndexType = {
    OTHER: 'OTHER' as IndexType,
    UFIR: 'UFIR' as IndexType,
    URV: 'URV' as IndexType,
    ITRD: 'ITRD' as IndexType,
    SELIC: 'SELIC' as IndexType,
    CONTRIBUTIONSALARYCORRECTION: 'CONTRIBUTION_SALARY_CORRECTION' as IndexType,
    SAVINGSCORRECTION: 'SAVINGS_CORRECTION' as IndexType,
    CURRENCY: 'CURRENCY' as IndexType
};
