/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type InformationType = 'CUMULATIVE' | 'PERCENTAGE' | 'FIXED_PERCENTEGE' | 'DAILY_VALUE' | 'MONTHLY_VALUE';

export const InformationType = {
    CUMULATIVE: 'CUMULATIVE' as InformationType,
    PERCENTAGE: 'PERCENTAGE' as InformationType,
    FIXEDPERCENTEGE: 'FIXED_PERCENTEGE' as InformationType,
    DAILYVALUE: 'DAILY_VALUE' as InformationType,
    MONTHLYVALUE: 'MONTHLY_VALUE' as InformationType
};
