/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type KinshipDegreeType = 'Adopted' | 'Child' | 'Concubine' | 'ExSpouse' | 'ExPartner' | 'Grandparent' | 'Grandchild' | 'GreatGrandparent' | 'GreatGrandchild' | 'Guardianship' | 'NephewNiece' | 'Other' | 'Parent' | 'FatherInLaw' | 'Partner' | 'Pensioners' | 'Pupil' | 'Sibling' | 'SonDaughterInLaw' | 'Spouse' | 'Stepfather' | 'Stepmother' | 'Stepchild' | 'Trusted' | 'UncleAunt' | 'Tutor';

export const KinshipDegreeType = {
    Adopted: 'Adopted' as KinshipDegreeType,
    Child: 'Child' as KinshipDegreeType,
    Concubine: 'Concubine' as KinshipDegreeType,
    ExSpouse: 'ExSpouse' as KinshipDegreeType,
    ExPartner: 'ExPartner' as KinshipDegreeType,
    Grandparent: 'Grandparent' as KinshipDegreeType,
    Grandchild: 'Grandchild' as KinshipDegreeType,
    GreatGrandparent: 'GreatGrandparent' as KinshipDegreeType,
    GreatGrandchild: 'GreatGrandchild' as KinshipDegreeType,
    Guardianship: 'Guardianship' as KinshipDegreeType,
    NephewNiece: 'NephewNiece' as KinshipDegreeType,
    Other: 'Other' as KinshipDegreeType,
    Parent: 'Parent' as KinshipDegreeType,
    FatherInLaw: 'FatherInLaw' as KinshipDegreeType,
    Partner: 'Partner' as KinshipDegreeType,
    Pensioners: 'Pensioners' as KinshipDegreeType,
    Pupil: 'Pupil' as KinshipDegreeType,
    Sibling: 'Sibling' as KinshipDegreeType,
    SonDaughterInLaw: 'SonDaughterInLaw' as KinshipDegreeType,
    Spouse: 'Spouse' as KinshipDegreeType,
    Stepfather: 'Stepfather' as KinshipDegreeType,
    Stepmother: 'Stepmother' as KinshipDegreeType,
    Stepchild: 'Stepchild' as KinshipDegreeType,
    Trusted: 'Trusted' as KinshipDegreeType,
    UncleAunt: 'UncleAunt' as KinshipDegreeType,
    Tutor: 'Tutor' as KinshipDegreeType
};
