/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MaritalStatusType = 'Single' | 'Married' | 'Divorced' | 'Widower' | 'Concubinage' | 'Separated' | 'StableUnion' | 'Others';

export const MaritalStatusType = {
    Single: 'Single' as MaritalStatusType,
    Married: 'Married' as MaritalStatusType,
    Divorced: 'Divorced' as MaritalStatusType,
    Widower: 'Widower' as MaritalStatusType,
    Concubinage: 'Concubinage' as MaritalStatusType,
    Separated: 'Separated' as MaritalStatusType,
    StableUnion: 'StableUnion' as MaritalStatusType,
    Others: 'Others' as MaritalStatusType
};
