/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.3.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type MethodPaymentType = 'BANK_CHECK' | 'MONEY' | 'MONEY_ORDER' | 'BANKING_RELATIONSHIP' | 'EXTERNAL';

export const MethodPaymentType = {
    BANKCHECK: 'BANK_CHECK' as MethodPaymentType,
    MONEY: 'MONEY' as MethodPaymentType,
    MONEYORDER: 'MONEY_ORDER' as MethodPaymentType,
    BANKINGRELATIONSHIP: 'BANKING_RELATIONSHIP' as MethodPaymentType,
    EXTERNAL: 'EXTERNAL' as MethodPaymentType
};
