/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { City } from './city';


export interface Neighborhood { 
    /**
     * Código do bairro
     */
    code?: number;
    city?: City;
    /**
     * Nome do bairro.
     */
    name?: string;
    /**
     * Id do bairro.
     */
    id?: string;
}
