/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubscriptionType } from './subscriptionType';


export interface Othercompany { 
    /**
     * Número da inscrição
     */
    subscriptionNumber?: number;
    subscriptionType?: SubscriptionType;
    /**
     * Data fim da validade
     */
    endDate?: string;
    /**
     * Número inscrição CNO
     */
    subscriptionNumberCNO?: number;
    /**
     * Nome da outra empresa
     */
    name?: string;
    /**
     * Apelido da outra empresa
     */
    nickname?: string;
    /**
     * Id da outra empresa
     */
    id?: string;
    /**
     * Inscrição no CAEPF (número)
     */
    subscriptionNumberCAEPF?: number;
    /**
     * Data de inicio da validade
     */
    startDate?: string;
}
