/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: ${version}
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Person { 
    /**
     * Primeiro nome
     */
    firstname?: string;
    /**
     * Id do upload da foto da g7
     */
    attachment?: string;
    /**
     * Segundo nome
     */
    middlename?: string;
    /**
     * Id da pessoa
     */
    id?: string;
    /**
     * Último nome
     */
    lastname?: string;
}
