/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PhoneType = 'PERSONAL' | 'PROFESSIONAL' | 'MOBILE' | 'BUSINESS_FAX' | 'PERSONAL_FAX' | 'OTHER';

export const PhoneType = {
    PERSONAL: 'PERSONAL' as PhoneType,
    PROFESSIONAL: 'PROFESSIONAL' as PhoneType,
    MOBILE: 'MOBILE' as PhoneType,
    BUSINESSFAX: 'BUSINESS_FAX' as PhoneType,
    PERSONALFAX: 'PERSONAL_FAX' as PhoneType,
    OTHER: 'OTHER' as PhoneType
};
