/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PhoneType } from './phoneType';


export interface Phone { 
    /**
     * Número do telefone
     */
    number?: string;
    phoneType?: PhoneType;
    /**
     * Ramal do telefone
     */
    extention?: string;
    /**
     * Código do país (DDI)
     */
    internationalCode?: string;
    /**
     * Código da localidade (DDD)
     */
    localCode?: string;
    /**
     * Id da entidade
     */
    id?: string;
}
