/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type SalaryAdvancedType = 'YES' | 'NO' | 'PERCENTAGE';

export const SalaryAdvancedType = {
    YES: 'YES' as SalaryAdvancedType,
    NO: 'NO' as SalaryAdvancedType,
    PERCENTAGE: 'PERCENTAGE' as SalaryAdvancedType
};
