/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type Salary13Type = 'YES' | 'NO' | 'PARTIAL';

export const Salary13Type = {
    YES: 'YES' as Salary13Type,
    NO: 'NO' as Salary13Type,
    PARTIAL: 'PARTIAL' as Salary13Type
};
