/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type SchoolGradeType = 'TYPE_1' | 'TYPE_2' | 'TYPE_3' | 'TYPE_4' | 'TYPE_5' | 'TYPE_6' | 'TYPE_7' | 'TYPE_8' | 'TYPE_9' | 'TYPE_10' | 'TYPE_11' | 'TYPE_12' | 'TYPE_13' | 'TYPE_14' | 'TYPE_15' | 'TYPE_16' | 'TYPE_17';

export const SchoolGradeType = {
    _1: 'TYPE_1' as SchoolGradeType,
    _2: 'TYPE_2' as SchoolGradeType,
    _3: 'TYPE_3' as SchoolGradeType,
    _4: 'TYPE_4' as SchoolGradeType,
    _5: 'TYPE_5' as SchoolGradeType,
    _6: 'TYPE_6' as SchoolGradeType,
    _7: 'TYPE_7' as SchoolGradeType,
    _8: 'TYPE_8' as SchoolGradeType,
    _9: 'TYPE_9' as SchoolGradeType,
    _10: 'TYPE_10' as SchoolGradeType,
    _11: 'TYPE_11' as SchoolGradeType,
    _12: 'TYPE_12' as SchoolGradeType,
    _13: 'TYPE_13' as SchoolGradeType,
    _14: 'TYPE_14' as SchoolGradeType,
    _15: 'TYPE_15' as SchoolGradeType,
    _16: 'TYPE_16' as SchoolGradeType,
    _17: 'TYPE_17' as SchoolGradeType
};
