/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type SubscriptionType = 'CNPJ' | 'CEI' | 'CPF' | 'INCRA';

export const SubscriptionType = {
    CNPJ: 'CNPJ' as SubscriptionType,
    CEI: 'CEI' as SubscriptionType,
    CPF: 'CPF' as SubscriptionType,
    INCRA: 'INCRA' as SubscriptionType
};
