/**
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.2.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dependent } from './dependent';


export interface Tutelage { 
    /**
     * Data final da tutela
     */
    endDate?: string;
    /**
     * Id do tutelado
     */
    id?: string;
    dependent?: Dependent;
    /**
     * Data de inicio da tutela
     */
    startDate?: string;
}
